// Copyright (C) 2002-2024 Joshua Kriegshauser
// All rights reserved.
#ifndef codepageH
#define codepageH
const OPCODE Z80::_codepage[][256] = {
  { /* codepage 0 */
    { "nop",    0x00, amNA,       amNA,       NULL,       4, 1, -1 },
    { "ld",     0x01, amREGBC,    amIMMEDIATEEX,LDDDNN,   0, 1, -1 },
    { "ld",     0x02, amREGINDBC, amREGA,     LDxA,       0, 1, -1 },
    { "inc",    0x03, amREGBC,    amNA,       INC16,      0, 1, -1 },
    { "inc",    0x04, amREGB,     amNA,       INC8,       0, 1, -1 },
    { "dec",    0x05, amREGB,     amNA,       DEC8,       0, 1, -1 },
    { "ld",     0x06, amREGB,     amIMMEDIATE,LDRN,       0, 1, -1 },
    { "rlca",   0x07, amREGA,     amNA,       RxCA,       0, 1, -1 },
    { "ex",     0x08, amREGAF,    amREGAF_,   EX,         0, 1, -1 },
    { "add",    0x09, amREGHL,    amREGBC,    ADD16,      0, 1, -1 },
    { "ld",     0x0A, amREGA,     amREGINDBC, LDA,        0, 1, -1 },
    { "dec",    0x0B, amREGBC,    amNA,       DEC16,      0, 1, -1 },
    { "inc",    0x0C, amREGC,     amNA,       INC8,       0, 1, -1 },
    { "dec",    0x0D, amREGC,     amNA,       DEC8,       0, 1, -1 },
    { "ld",     0x0E, amREGC,     amIMMEDIATE,LDRN,       0, 1, -1 },
    { "rrca",   0x0F, amREGA,     amNA,       RxCA,       0, 1, -1 },
    { "djnz",   0x10, amRELATIVE, amNA,       JR,         0, 1, -1 },
    { "ld",     0x11, amREGDE,    amIMMEDIATEEX,LDDDNN,   0, 1, -1 },
    { "ld",     0x12, amREGINDDE, amREGA,     LDxA,       0, 1, -1 },
    { "inc",    0x13, amREGDE,    amNA,       INC16,      0, 1, -1 },
    { "inc",    0x14, amREGD,     amNA,       INC8,       0, 1, -1 },
    { "dec",    0x15, amREGD,     amNA,       DEC8,       0, 1, -1 },
    { "ld",     0x16, amREGD,     amIMMEDIATE,LDRN,       0, 1, -1 },
    { "rla",    0x17, amREGA,     amNA,       RxA,        0, 1, -1 },
    { "jr",     0x18, amRELATIVE, amNA,       JR,         0, 1, -1 },
    { "add",    0x19, amREGHL,    amREGDE,    ADD16,      0, 1, -1 },
    { "ld",     0x1A, amREGA,     amREGINDDE, LDA,        0, 1, -1 },
    { "dec",    0x1B, amREGDE,    amNA,       DEC16,      0, 1, -1 },
    { "inc",    0x1C, amREGE,     amNA,       INC8,       0, 1, -1 },
    { "dec",    0x1D, amREGE,     amNA,       DEC8,       0, 1, -1 },
    { "ld",     0x1E, amREGE,     amIMMEDIATE,LDRN,       0, 1, -1 },
    { "rra",    0x1F, amREGA,     amNA,       RxA,        0, 1, -1 },
    { "jr nz,", 0x20, amRELATIVE, amNA,       JR,         0, 1, -1 },
    { "ld",     0x21, amREGHL,    amIMMEDIATEEX,LDDDNN,   0, 1, -1 },
    { "ld",     0x22, amEXTENDED, amREGHL,    LDNNIDD,    0, 1, -1 },
    { "inc",    0x23, amREGHL,    amNA,       INC16,      0, 1, -1 },
    { "inc",    0x24, amREGH,     amNA,       INC8,       0, 1, -1 },
    { "dec",    0x25, amREGH,     amNA,       DEC8,       0, 1, -1 },
    { "ld",     0x26, amREGH,     amIMMEDIATE,LDRN,       0, 1, -1 },
    { "daa",    0x27, amIMPLIED,  amNA,       DAA,        0, 1, -1 },
    { "jr z,",  0x28, amRELATIVE, amNA,       JR,         0, 1, -1 },
    { "add",    0x29, amREGHL,    amREGHL,    ADD16,      0, 1, -1 },
    { "ld",     0x2A, amREGHL,    amEXTENDED, LDDDNNI,    0, 1, -1 },
    { "dec",    0x2B, amREGHL,    amNA,       DEC16,      0, 1, -1 },
    { "inc",    0x2C, amREGL,     amNA,       INC8,       0, 1, -1 },
    { "dec",    0x25, amREGL,     amNA,       DEC8,       0, 1, -1 },
    { "ld",     0x2E, amREGL,     amIMMEDIATE,LDRN,       0, 1, -1 },
    { "cpl",    0x2F, amIMPLIED,  amNA,       CPL,        0, 1, -1 },
    { "jr nc,", 0x30, amRELATIVE, amNA,       JR,         0, 1, -1 },
    { "ld",     0x31, amREGSP,    amIMMEDIATEEX,LDDDNN,   0, 1, -1 },
    { "ld",     0x32, amEXTENDED, amREGA,     LDxA,       0, 1, -1 },
    { "inc",    0x33, amREGSP,    amNA,       INC16,      0, 1, -1 },
    { "inc",    0x34, amREGINDHL, amNA,       INC8,       0, 1, -1 },
    { "dec",    0x35, amREGINDHL, amNA,       DEC8,       0, 1, -1 },
    { "ld",     0x36, amREGINDHL, amIMMEDIATE,LDHLN,      0, 1, -1 },
    { "scf",    0x37, amNA,       amNA,       SCF,        0, 1, -1 },
    { "jr c,",  0x38, amRELATIVE, amNA,       JR,         0, 1, -1 },
    { "add",    0x39, amREGHL,    amREGSP,    ADD16,      0, 1, -1 },
    { "ld",     0x3A, amREGA,     amEXTENDED, LDA,        0, 1, -1 },
    { "dec",    0x3B, amREGSP,    amNA,       DEC16,      0, 1, -1 },
    { "inc",    0x3C, amREGA,     amNA,       INC8,       0, 1, -1 },
    { "dec",    0x3D, amREGA,     amNA,       DEC8,       0, 1, -1 },
    { "ld",     0x3E, amREGA,     amIMMEDIATE,LDRN,       0, 1, -1 },
    { "ccf",    0x3F, amNA,       amNA,       CCF,        0, 1, -1 },
    { "ld",     0x40, amREGB,     amREGB,     LDREGS,     0, 1, -1 },
    { "ld",     0x41, amREGB,     amREGC,     LDREGS,     0, 1, -1 },
    { "ld",     0x42, amREGB,     amREGD,     LDREGS,     0, 1, -1 },
    { "ld",     0x43, amREGB,     amREGE,     LDREGS,     0, 1, -1 },
    { "ld",     0x44, amREGB,     amREGH,     LDREGS,     0, 1, -1 },
    { "ld",     0x45, amREGB,     amREGL,     LDREGS,     0, 1, -1 },
    { "ld",     0x46, amREGB,     amREGINDHL, LDRHL,      0, 1, -1 },
    { "ld",     0x47, amREGB,     amREGA,     LDREGS,     0, 1, -1 },
    { "ld",     0x48, amREGC,     amREGB,     LDREGS,     0, 1, -1 },
    { "ld",     0x49, amREGC,     amREGC,     LDREGS,     0, 1, -1 },
    { "ld",     0x4A, amREGC,     amREGD,     LDREGS,     0, 1, -1 },
    { "ld",     0x4B, amREGC,     amREGE,     LDREGS,     0, 1, -1 },
    { "ld",     0x4C, amREGC,     amREGH,     LDREGS,     0, 1, -1 },
    { "ld",     0x4D, amREGC,     amREGL,     LDREGS,     0, 1, -1 },
    { "ld",     0x4E, amREGC,     amREGINDHL, LDRHL,      0, 1, -1 },
    { "ld",     0x4F, amREGC,     amREGA,     LDREGS,     0, 1, -1 },
    { "ld",     0x50, amREGD,     amREGB,     LDREGS,     0, 1, -1 },
    { "ld",     0x51, amREGD,     amREGC,     LDREGS,     0, 1, -1 },
    { "ld",     0x52, amREGD,     amREGD,     LDREGS,     0, 1, -1 },
    { "ld",     0x53, amREGD,     amREGE,     LDREGS,     0, 1, -1 },
    { "ld",     0x54, amREGD,     amREGH,     LDREGS,     0, 1, -1 },
    { "ld",     0x55, amREGD,     amREGL,     LDREGS,     0, 1, -1 },
    { "ld",     0x56, amREGD,     amREGINDHL, LDRHL,      0, 1, -1 },
    { "ld",     0x57, amREGD,     amREGA,     LDREGS,     0, 1, -1 },
    { "ld",     0x58, amREGE,     amREGB,     LDREGS,     0, 1, -1 },
    { "ld",     0x59, amREGE,     amREGC,     LDREGS,     0, 1, -1 },
    { "ld",     0x5A, amREGE,     amREGD,     LDREGS,     0, 1, -1 },
    { "ld",     0x5B, amREGE,     amREGE,     LDREGS,     0, 1, -1 },
    { "ld",     0x5C, amREGE,     amREGH,     LDREGS,     0, 1, -1 },
    { "ld",     0x5D, amREGE,     amREGL,     LDREGS,     0, 1, -1 },
    { "ld",     0x5E, amREGE,     amREGINDHL, LDRHL,      0, 1, -1 },
    { "ld",     0x5F, amREGE,     amREGA,     LDREGS,     0, 1, -1 },
    { "ld",     0x60, amREGH,     amREGB,     LDREGS,     0, 1, -1 },
    { "ld",     0x61, amREGH,     amREGC,     LDREGS,     0, 1, -1 },
    { "ld",     0x62, amREGH,     amREGD,     LDREGS,     0, 1, -1 },
    { "ld",     0x63, amREGH,     amREGE,     LDREGS,     0, 1, -1 },
    { "ld",     0x64, amREGH,     amREGH,     LDREGS,     0, 1, -1 },
    { "ld",     0x65, amREGH,     amREGL,     LDREGS,     0, 1, -1 },
    { "ld",     0x66, amREGH,     amREGINDHL, LDRHL,      0, 1, -1 },
    { "ld",     0x67, amREGH,     amREGA,     LDREGS,     0, 1, -1 },
    { "ld",     0x68, amREGL,     amREGB,     LDREGS,     0, 1, -1 },
    { "ld",     0x69, amREGL,     amREGC,     LDREGS,     0, 1, -1 },
    { "ld",     0x6A, amREGL,     amREGD,     LDREGS,     0, 1, -1 },
    { "ld",     0x6B, amREGL,     amREGE,     LDREGS,     0, 1, -1 },
    { "ld",     0x6C, amREGL,     amREGH,     LDREGS,     0, 1, -1 },
    { "ld",     0x6D, amREGL,     amREGL,     LDREGS,     0, 1, -1 },
    { "ld",     0x6E, amREGL,     amREGINDHL, LDRHL,      0, 1, -1 },
    { "ld",     0x6F, amREGL,     amREGA,     LDREGS,     0, 1, -1 },
    { "ld",     0x70, amREGINDHL, amREGB,     LDHLR,      0, 1, -1 },
    { "ld",     0x71, amREGINDHL, amREGC,     LDHLR,      0, 1, -1 },
    { "ld",     0x72, amREGINDHL, amREGD,     LDHLR,      0, 1, -1 },
    { "ld",     0x73, amREGINDHL, amREGE,     LDHLR,      0, 1, -1 },
    { "ld",     0x74, amREGINDHL, amREGH,     LDHLR,      0, 1, -1 },
    { "ld",     0x75, amREGINDHL, amREGL,     LDHLR,      0, 1, -1 },
    { "halt",   0x76, amNA,       amNA,       HALT,       0, 1, -1 },
    { "ld",     0x77, amREGINDHL, amREGA,     LDHLR,      0, 1, -1 },
    { "ld",     0x78, amREGA,     amREGB,     LDREGS,     0, 1, -1 },
    { "ld",     0x79, amREGA,     amREGC,     LDREGS,     0, 1, -1 },
    { "ld",     0x7A, amREGA,     amREGD,     LDREGS,     0, 1, -1 },
    { "ld",     0x7B, amREGA,     amREGE,     LDREGS,     0, 1, -1 },
    { "ld",     0x7C, amREGA,     amREGH,     LDREGS,     0, 1, -1 },
    { "ld",     0x7D, amREGA,     amREGL,     LDREGS,     0, 1, -1 },
    { "ld",     0x7E, amREGA,     amREGINDHL, LDRHL,      0, 1, -1 },
    { "ld",     0x7F, amREGA,     amREGA,     LDREGS,     0, 1, -1 },
    { "add",    0x80, amREGA,     amREGB,     ADD8,       0, 1, -1 },
    { "add",    0x81, amREGA,     amREGC,     ADD8,       0, 1, -1 },
    { "add",    0x82, amREGA,     amREGD,     ADD8,       0, 1, -1 },
    { "add",    0x83, amREGA,     amREGE,     ADD8,       0, 1, -1 },
    { "add",    0x84, amREGA,     amREGH,     ADD8,       0, 1, -1 },
    { "add",    0x85, amREGA,     amREGL,     ADD8,       0, 1, -1 },
    { "add",    0x86, amREGA,     amREGINDHL, ADD8,       0, 1, -1 },
    { "add",    0x87, amREGA,     amREGA,     ADD8,       0, 1, -1 },
    { "adc",    0x88, amREGA,     amREGB,     ADC8,       0, 1, -1 },
    { "adc",    0x89, amREGA,     amREGC,     ADC8,       0, 1, -1 },
    { "adc",    0x8A, amREGA,     amREGD,     ADC8,       0, 1, -1 },
    { "adc",    0x8B, amREGA,     amREGE,     ADC8,       0, 1, -1 },
    { "adc",    0x8C, amREGA,     amREGH,     ADC8,       0, 1, -1 },
    { "adc",    0x8D, amREGA,     amREGL,     ADC8,       0, 1, -1 },
    { "adc",    0x8E, amREGA,     amREGINDHL, ADC8,       0, 1, -1 },
    { "adc",    0x8F, amREGA,     amREGA,     ADC8,       0, 1, -1 },
    { "sub",    0x90, amREGA,     amREGB,     SUB8,       0, 1, -1 },
    { "sub",    0x91, amREGA,     amREGC,     SUB8,       0, 1, -1 },
    { "sub",    0x92, amREGA,     amREGD,     SUB8,       0, 1, -1 },
    { "sub",    0x93, amREGA,     amREGE,     SUB8,       0, 1, -1 },
    { "sub",    0x94, amREGA,     amREGH,     SUB8,       0, 1, -1 },
    { "sub",    0x95, amREGA,     amREGL,     SUB8,       0, 1, -1 },
    { "sub",    0x96, amREGA,     amREGINDHL, SUB8,       0, 1, -1 },
    { "sub",    0x97, amREGA,     amREGA,     SUB8,       0, 1, -1 },
    { "sbc",    0x98, amREGA,     amREGB,     SBC8,       0, 1, -1 },
    { "sbc",    0x99, amREGA,     amREGC,     SBC8,       0, 1, -1 },
    { "sbc",    0x9A, amREGA,     amREGD,     SBC8,       0, 1, -1 },
    { "sbc",    0x9B, amREGA,     amREGE,     SBC8,       0, 1, -1 },
    { "sbc",    0x9C, amREGA,     amREGH,     SBC8,       0, 1, -1 },
    { "sbc",    0x9D, amREGA,     amREGL,     SBC8,       0, 1, -1 },
    { "sbc",    0x9E, amREGA,     amREGINDHL, SBC8,       0, 1, -1 },
    { "sbc",    0x9F, amREGA,     amREGA,     SBC8,       0, 1, -1 },
    { "and",    0xA0, amREGB,     amNA,       AND8,       0, 1, -1 },
    { "and",    0xA1, amREGC,     amNA,       AND8,       0, 1, -1 },
    { "and",    0xA2, amREGD,     amNA,       AND8,       0, 1, -1 },
    { "and",    0xA3, amREGE,     amNA,       AND8,       0, 1, -1 },
    { "and",    0xA4, amREGH,     amNA,       AND8,       0, 1, -1 },
    { "and",    0xA5, amREGL,     amNA,       AND8,       0, 1, -1 },
    { "and",    0xA6, amREGINDHL, amNA,       AND8,       0, 1, -1 },
    { "and",    0xA7, amREGA,     amNA,       AND8,       0, 1, -1 },
    { "xor",    0xA8, amREGB,     amNA,       XOR8,       0, 1, -1 },
    { "xor",    0xA9, amREGC,     amNA,       XOR8,       0, 1, -1 },
    { "xor",    0xAA, amREGD,     amNA,       XOR8,       0, 1, -1 },
    { "xor",    0xAB, amREGE,     amNA,       XOR8,       0, 1, -1 },
    { "xor",    0xAC, amREGH,     amNA,       XOR8,       0, 1, -1 },
    { "xor",    0xAD, amREGL,     amNA,       XOR8,       0, 1, -1 },
    { "xor",    0xAE, amREGINDHL, amNA,       XOR8,       0, 1, -1 },
    { "xor",    0xAF, amREGA,     amNA,       XOR8,       0, 1, -1 },
    { "or",     0xB0, amREGB,     amNA,       OR8,        0, 1, -1 },
    { "or",     0xB1, amREGC,     amNA,       OR8,        0, 1, -1 },
    { "or",     0xB2, amREGD,     amNA,       OR8,        0, 1, -1 },
    { "or",     0xB3, amREGE,     amNA,       OR8,        0, 1, -1 },
    { "or",     0xB4, amREGH,     amNA,       OR8,        0, 1, -1 },
    { "or",     0xB5, amREGL,     amNA,       OR8,        0, 1, -1 },
    { "or",     0xB6, amREGINDHL, amNA,       OR8,        0, 1, -1 },
    { "or",     0xB7, amREGA,     amNA,       OR8,        0, 1, -1 },
    { "cp",     0xB8, amREGB,     amNA,       CP,         0, 1, -1 },
    { "cp",     0xB9, amREGC,     amNA,       CP,         0, 1, -1 },
    { "cp",     0xBA, amREGD,     amNA,       CP,         0, 1, -1 },
    { "cp",     0xBB, amREGE,     amNA,       CP,         0, 1, -1 },
    { "cp",     0xBC, amREGH,     amNA,       CP,         0, 1, -1 },
    { "cp",     0xBD, amREGL,     amNA,       CP,         0, 1, -1 },
    { "cp",     0xBE, amREGINDHL, amNA,       CP,         0, 1, -1 },
    { "cp",     0xBF, amREGA,     amNA,       CP,         0, 1, -1 },
    { "ret nz", 0xC0, amNA,       amNA,       RET,        0, 1, -1 },
    { "pop",    0xC1, amREGBC,    amNA,       POPQQ,      0, 1, -1 },
    { "jp nz,", 0xC2, amIMMEDIATEEX, amNA,    JP,         0, 1, -1 },
    { "jp",     0xC3, amIMMEDIATEEX, amNA,    JP,         0, 1, -1 },
    { "call nz,",0xC4,amIMMEDIATEEX, amNA,    CALL,       0, 1, -1 },
    { "push",   0xC5, amREGBC,    amNA,       PUSHQQ,     0, 1, -1 },
    { "add",    0xC6, amREGA,     amIMMEDIATE,ADD8,       0, 1, -1 },
    { "rst",    0xC7, amPAGEZERO, amNA,       CALL,       0, 1, -1 },
    { "ret z",  0xC8, amNA,       amNA,       RET,        0, 1, -1 },
    { "ret",    0xC9, amNA,       amNA,       RET,        0, 1, -1 },
    { "jp z,",  0xCA, amIMMEDIATEEX, amNA,    JP,         0, 1, -1 },
    { "",       0xCB, amNA,       amNA,       NULL,       0, 1,  4 },
    { "call z,",0xCC, amIMMEDIATEEX, amNA,    CALL,       0, 1, -1 },
    { "call",   0xCD, amIMMEDIATEEX, amNA,    CALL,       0, 1, -1 },
    { "adc",    0xCE, amREGA,     amIMMEDIATE,ADC8,       0, 1, -1 },
    { "rst",    0xCF, amPAGEZERO, amNA,       CALL,       0, 1, -1 },
    { "ret nc", 0xD0, amNA,       amNA,       RET,        0, 1, -1 },
    { "pop",    0xD1, amREGDE,    amNA,       POPQQ,      0, 1, -1 },
    { "jp nc,", 0xD2, amIMMEDIATEEX, amNA,    JP,         0, 1, -1 },
    { "out",    0xD3, amIMMEDIATE,amREGA,     OUTPORT,    0, 1, -1 },
    { "call nc,",0xD4,amIMMEDIATEEX, amNA,    CALL,       0, 1, -1 },
    { "push",   0xD5, amREGDE,    amNA,       PUSHQQ,     0, 1, -1 },
    { "sub",    0xD6, amREGA,     amIMMEDIATE,SUB8,       0, 1, -1 },
    { "rst",    0xD7, amPAGEZERO, amNA,       CALL,       0, 1, -1 },
    { "ret c",  0xD8, amNA,       amNA,       RET,        0, 1, -1 },
    { "exx",    0xD9, amNA,       amNA,       EX,         0, 1, -1 },
    { "jp c,",  0xDA, amIMMEDIATEEX, amNA,    JP,         0, 1, -1 },
    { "in",     0xDB, amREGA,     amIMMEDIATE,INPORT,     0, 1, -1 },
    { "call c,",0xDC, amIMMEDIATEEX, amNA,    CALL,       0, 1, -1 },
    { "",       0xDD, amNA,       amNA,       NULL,       0, 1,  2 },
    { "sbc",    0xDE, amREGA,     amIMMEDIATE,SBC8,       0, 1, -1 },
    { "rst",    0xDF, amPAGEZERO, amNA,       CALL,       0, 1, -1 },
    { "ret po", 0xE0, amNA,       amNA,       RET,        0, 1, -1 },
    { "pop",    0xE1, amREGHL,    amNA,       POPQQ,      0, 1, -1 },
    { "jp po,", 0xE2, amIMMEDIATEEX, amNA,    JP,         0, 1, -1 },
    { "ex",     0xE3, amREGINDSP, amREGHL,    EX,         0, 1, -1 },
    { "call po,",0xE4,amIMMEDIATEEX, amNA,    CALL,       0, 1, -1 },
    { "push",   0xE5, amREGHL,    amNA,       PUSHQQ,     0, 1, -1 },
    { "and",    0xE6, amIMMEDIATE,amNA,       AND8,       0, 1, -1 },
    { "rst",    0xE7, amPAGEZERO, amNA,       CALL,       0, 1, -1 },
    { "ret pe", 0xE8, amNA,       amNA,       RET,        0, 1, -1 },
    { "jp",     0xE9, amREGINDHL, amNA,       JP,         0, 1, -1 },
    { "jp pe,", 0xEA, amIMMEDIATEEX, amNA,    JP,         0, 1, -1 },
    { "ex",     0xEB, amREGDE,    amREGHL,    EX,         0, 1, -1 },
    { "call pe,",0xEC,amIMMEDIATEEX, amNA,    CALL,       0, 1, -1 },
    { "",       0xED, amNA,       amNA,       NULL,       0, 1,  3 },
    { "xor",    0xEE, amIMMEDIATE,amNA,       XOR8,       0, 1, -1 },
    { "rst",    0xEF, amPAGEZERO, amNA,       CALL,       0, 1, -1 },
    { "ret p",  0xF0, amNA,       amNA,       RET,        0, 1, -1 },
    { "pop",    0xF1, amREGAF,    amNA,       POPQQ,      0, 1, -1 },
    { "jp p,",  0xF2, amIMMEDIATEEX, amNA,    JP,         0, 1, -1 },
    { "di",     0xF3, amNA,       amNA,       DI,         0, 1, -1 },
    { "call p,",0xF4, amIMMEDIATEEX, amNA,    CALL,       0, 1, -1 },
    { "push",   0xF5, amREGAF,    amNA,       PUSHQQ,     0, 1, -1 },
    { "or",     0xF6, amIMMEDIATE,amNA,       OR8,        0, 1, -1 },
    { "rst",    0xF7, amPAGEZERO, amNA,       CALL,       0, 1, -1 },
    { "ret m",  0xF8, amNA,       amNA,       RET,        0, 1, -1 },
    { "ld",     0xF9, amREGSP,    amREGHL,    LDSP,       0, 1, -1 },
    { "jp m,",  0xFA, amIMMEDIATEEX, amNA,    JP,         0, 1, -1 },
    { "ei",     0xFB, amNA,       amNA,       EI,         0, 1, -1 },
    { "call m,",0xFC, amIMMEDIATEEX, amNA,    CALL,       0, 1, -1 },
    { "",       0xFD, amNA,       amNA,       NULL,       0, 1,  1 },
    { "cp",     0xFE, amIMMEDIATE,amNA,       CP,         0, 1, -1 },
    { "rst",    0xFF, amPAGEZERO, amNA,       CALL,       0, 1, -1 },
  },
  { /* 0xFD codepage (1) */
    { "add",    0x09, amREGIY,    amREGBC,    ADD16,      0, 2, -1 },
    { "add",    0x19, amREGIY,    amREGDE,    ADD16,      0, 2, -1 },
    { "ld",     0x21, amREGIY,    amIMMEDIATEEX,LDINN,    0, 2, -1 },
    { "ld",     0x22, amEXTENDED, amREGIY,    LDNNII,     0, 2, -1 },
    { "inc",    0x23, amREGIY,    amNA,       INC16,      0, 2, -1 },
    { "add",    0x29, amREGIY,    amREGIY,    ADD16,      0, 2, -1 },
    { "ld",     0x2A, amREGIY,    amEXTENDED, LDINNI,     0, 2, -1 },
    { "dec",    0x2B, amREGIY,    amNA,       DEC16,      0, 2, -1 },
    { "inc",    0x34, amINDEXY,   amNA,       INC8,       0, 2, -1 },
    { "dec",    0x35, amINDEXY,   amNA,       DEC8,       0, 2, -1 },
    { "ld",     0x36, amINDEXY,   amIMMEDIATE,LDIN,       0, 2, -1 },
    { "add",    0x39, amREGIY,    amREGSP,    ADD16,      0, 2, -1 },
    { "ld",     0x46, amREGB,     amINDEXY,   LDRI,       0, 2, -1 },
    { "ld",     0x4E, amREGC,     amINDEXY,   LDRI,       0, 2, -1 },
    { "ld",     0x56, amREGD,     amINDEXY,   LDRI,       0, 2, -1 },
    { "ld",     0x5E, amREGE,     amINDEXY,   LDRI,       0, 2, -1 },
    { "ld",     0x66, amREGH,     amINDEXY,   LDRI,       0, 2, -1 },
    { "ld",     0x6E, amREGL,     amINDEXY,   LDRI,       0, 2, -1 },
    { "ld",     0x70, amINDEXY,   amREGB,     LDIxR,      0, 2, -1 },
    { "ld",     0x71, amINDEXY,   amREGC,     LDIxR,      0, 2, -1 },
    { "ld",     0x72, amINDEXY,   amREGD,     LDIxR,      0, 2, -1 },
    { "ld",     0x73, amINDEXY,   amREGE,     LDIxR,      0, 2, -1 },
    { "ld",     0x74, amINDEXY,   amREGH,     LDIxR,      0, 2, -1 },
    { "ld",     0x75, amINDEXY,   amREGL,     LDIxR,      0, 2, -1 },
    { "ld",     0x77, amINDEXY,   amREGA,     LDIxR,      0, 2, -1 },
    { "ld",     0x7E, amREGA,     amINDEXY,   LDRI,       0, 2, -1 },
    { "add",    0x86, amREGA,     amINDEXY,   ADD8,       0, 2, -1 },
    { "adc",    0x8E, amREGA,     amINDEXY,   ADC8,       0, 2, -1 },
    { "sub",    0x96, amREGA,     amINDEXY,   SUB8,       0, 2, -1 },
    { "sbc",    0x9E, amREGA,     amINDEXY,   SBC8,       0, 2, -1 },
    { "and",    0xA6, amINDEXY,   amNA,       AND8,       0, 2, -1 },
    { "xor",    0xAE, amINDEXY,   amNA,       XOR8,       0, 2, -1 },
    { "or",     0xB6, amINDEXY,   amNA,       OR8,        0, 2, -1 },
    { "cp",     0xBE, amINDEXY,   amNA,       CP,         0, 2, -1 },
    { NULL,     0xCB, amINDEXY,   amSKIPONE,  FDCB,       0, 2, -1 },
    { "pop",    0xE1, amREGIY,    amNA,       POPQQ,      0, 2, -1 },
    { "ex",     0xE3, amREGINDSP, amREGIY,    EX,         0, 2, -1 },
    { "push",   0xE5, amREGIY,    amNA,       PUSHQQ,     0, 2, -1 },
    { "jp",     0xE9, amREGINDIY, amNA,       JP,         0, 2, -1 },
    { "ld",     0xF9, amREGSP,    amREGIY,    LDSP,       0, 2, -1 },
  },
  { /* 0xDD codepage (2) */
    { "add",    0x09, amREGIX,    amREGBC,    ADD16,      0, 2, -1 },
    { "add",    0x19, amREGIX,    amREGDE,    ADD16,      0, 2, -1 },
    { "ld",     0x21, amREGIX,    amIMMEDIATEEX,LDINN,    0, 2, -1 },
    { "ld",     0x22, amEXTENDED, amREGIX,    LDNNII,     0, 2, -1 },
    { "inc",    0x23, amREGIX,    amNA,       INC16,      0, 2, -1 },
    { "add",    0x29, amREGIX,    amREGIX,    ADD16,      0, 2, -1 },
    { "ld",     0x2A, amREGIX,    amEXTENDED, LDINNI,     0, 2, -1 },
    { "dec",    0x2B, amREGIX,    amNA,       DEC16,      0, 2, -1 },
    { "inc",    0x34, amINDEXX,   amNA,       INC8,       0, 2, -1 },
    { "dec",    0x35, amINDEXX,   amNA,       DEC8,       0, 2, -1 },
    { "ld",     0x36, amINDEXX,   amIMMEDIATE,LDIN,       0, 2, -1 },
    { "add",    0x39, amREGIX,    amREGSP,    ADD16,      0, 2, -1 },
    { "ld",     0x46, amREGB,     amINDEXX,   LDRI,       0, 2, -1 },
    { "ld",     0x4E, amREGC,     amINDEXX,   LDRI,       0, 2, -1 },
    { "ld",     0x56, amREGD,     amINDEXX,   LDRI,       0, 2, -1 },
    { "ld",     0x5E, amREGE,     amINDEXX,   LDRI,       0, 2, -1 },
    { "ld",     0x66, amREGH,     amINDEXX,   LDRI,       0, 2, -1 },
    { "ld",     0x6E, amREGL,     amINDEXX,   LDRI,       0, 2, -1 },
    { "ld",     0x70, amINDEXX,   amREGB,     LDIxR,      0, 2, -1 },
    { "ld",     0x71, amINDEXX,   amREGC,     LDIxR,      0, 2, -1 },
    { "ld",     0x72, amINDEXX,   amREGD,     LDIxR,      0, 2, -1 },
    { "ld",     0x73, amINDEXX,   amREGE,     LDIxR,      0, 2, -1 },
    { "ld",     0x74, amINDEXX,   amREGH,     LDIxR,      0, 2, -1 },
    { "ld",     0x75, amINDEXX,   amREGL,     LDIxR,      0, 2, -1 },
    { "ld",     0x77, amINDEXX,   amREGA,     LDIxR,      0, 2, -1 },
    { "ld",     0x7E, amREGA,     amINDEXX,   LDRI,       0, 2, -1 },
    { "add",    0x86, amREGA,     amINDEXX,   ADD8,       0, 2, -1 },
    { "adc",    0x8E, amREGA,     amINDEXX,   ADC8,       0, 2, -1 },
    { "sub",    0x96, amREGA,     amINDEXX,   SUB8,       0, 2, -1 },
    { "sbc",    0x9E, amREGA,     amINDEXX,   SBC8,       0, 2, -1 },
    { "and",    0xA6, amINDEXX,   amNA,       AND8,       0, 2, -1 },
    { "xor",    0xAE, amINDEXX,   amNA,       XOR8,       0, 2, -1 },
    { "or",     0xB6, amINDEXX,   amNA,       OR8,        0, 2, -1 },
    { "cp",     0xBE, amINDEXX,   amNA,       CP,         0, 2, -1 },
    { NULL,     0xCB, amINDEXX,   amSKIPONE,  DDCB,       0, 2, -1 },
    { "pop",    0xE1, amREGIX,    amNA,       POPQQ,      0, 2, -1 },
    { "ex",     0xE3, amREGINDSP, amREGIX,    EX,         0, 2, -1 },
    { "push",   0xE5, amREGIX,    amNA,       PUSHQQ,     0, 2, -1 },
    { "jp",     0xE9, amREGINDIX, amNA,       JP,         0, 2, -1 },
    { "ld",     0xF9, amREGSP,    amREGIX,    LDSP,       0, 2, -1 },
  },
  { /* 0xED codepage (3) */
    { "in",     0x40, amREGB,     amREGC,     INPORT,     0, 2, -1 },
    { "out",    0x41, amREGC,     amREGB,     OUTPORT,    0, 2, -1 },
    { "sbc",    0x42, amREGHL,    amREGBC,    ADD16,      0, 2, -1 },
    { "ld",     0x43, amEXTENDED, amREGBC,    LDNNIDD,    0, 2, -1 },
    { "neg",    0x44, amIMPLIED,  amNA,       NEG,        0, 2, -1 },
    { "retn",   0x45, amNA,       amNA,       RET,        0, 2, -1 },
    { "im0",    0x46, amNA,       amNA,       IM,         0, 2, -1 },
    { "ld",     0x47, amREGI,     amREGA,     LDxA,       0, 2, -1 },
    { "in",     0x48, amREGC,     amREGC,     INPORT,     0, 2, -1 },
    { "out",    0x49, amREGC,     amREGC,     OUTPORT,    0, 2, -1 },
    { "adc",    0x4A, amREGHL,    amREGBC,    ADD16,      0, 2, -1 },
    { "ld",     0x4B, amREGBC,    amEXTENDED, LDDDNNI,    0, 2, -1 },
    { "reti",   0x4D, amNA,       amNA,       RET,        0, 2, -1 },
    { "ld",     0x4F, amREGR,     amREGA,     LDxA,       0, 2, -1 },
    { "in",     0x50, amREGD,     amREGC,     INPORT,     0, 2, -1 },
    { "out",    0x51, amREGC,     amREGD,     OUTPORT,    0, 2, -1 },
    { "sbc",    0x52, amREGHL,    amREGDE,    ADD16,      0, 2, -1 },
    { "ld",     0x53, amEXTENDED, amREGDE,    LDNNIDD,    0, 2, -1 },
    { "im1",    0x56, amNA,       amNA,       IM,         0, 2, -1 },
    { "ld",     0x57, amREGA,     amREGI,     LDA,        0, 2, -1 },
    { "in",     0x58, amREGE,     amREGC,     INPORT,     0, 2, -1 },
    { "out",    0x59, amREGC,     amREGE,     OUTPORT,    0, 2, -1 },
    { "adc",    0x5A, amREGHL,    amREGDE,    ADD16,      0, 2, -1 },
    { "ld",     0x5B, amREGDE,    amEXTENDED, LDDDNNI,    0, 2, -1 },
    { "im2",    0x5E, amNA,       amNA,       IM,         0, 2, -1 },
    { "ld a,r", 0x5F, amIMPLIED,  amIMPLIED,  LDA,        0, 2, -1 },
    { "in",     0x60, amREGH,     amREGC,     INPORT,     0, 2, -1 },
    { "out",    0x61, amREGC,     amREGH,     OUTPORT,    0, 2, -1 },
    { "sbc",    0x62, amREGHL,    amREGHL,    ADD16,      0, 2, -1 },
    { "rrd",    0x67, amIMPLIED,  amNA,       RxD,        0, 2, -1 },
    { "in",     0x68, amREGL,     amREGC,     INPORT,     0, 2, -1 },
    { "out",    0x69, amREGC,     amREGL,     OUTPORT,    0, 2, -1 },
    { "adc",    0x6A, amREGHL,    amREGHL,    ADD16,      0, 2, -1 },
    { "ld",     0x6B, amREGHL,    amEXTENDED, LDDDNNI,    0, 2, -1 },
    { "rld",    0x6F, amIMPLIED,  amNA,       RxD,        0, 2, -1 },
    { "sbc",    0x72, amREGHL,    amREGSP,    ADD16,      0, 2, -1 },
    { "ld",     0x73, amEXTENDED, amREGSP,    LDNNIDD,    0, 2, -1 },
    { "in",     0x78, amREGA,     amREGC,     INPORT,     0, 2, -1 },
    { "out",    0x79, amREGC,     amREGA,     OUTPORT,    0, 2, -1 },
    { "adc",    0x7A, amREGHL,    amREGSP,    ADD16,      0, 2, -1 },
    { "ld",     0x7B, amREGSP,    amEXTENDED, LDDDNNI,    0, 2, -1 },
    { "ldi",    0xA0, amNA,       amNA,       LDI,        0, 2, -1 },
    { "cpi",    0xA1, amNA,       amNA,       CPI,        0, 2, -1 },
    { "ini",    0xA2, amNA,       amNA,       INI,        0, 2, -1 },
    { "outi",   0xA3, amNA,       amNA,       OUTI,       0, 2, -1 },
    { "ldd",    0xA8, amNA,       amNA,       LDD,        0, 2, -1 },
    { "cpd",    0xA9, amNA,       amNA,       CPD,        0, 2, -1 },
    { "ind",    0xAA, amNA,       amNA,       IND,        0, 2, -1 },
    { "outd",   0xAB, amNA,       amNA,       OUTD,       0, 2, -1 },
    { "ldir",   0xB0, amNA,       amNA,       LDIR,       0, 2, -1 },
    { "cpir",   0xB1, amNA,       amNA,       CPIR,       0, 2, -1 },
    { "inir",   0xB2, amNA,       amNA,       INIR,       0, 2, -1 },
    { "otir",   0xB3, amNA,       amNA,       OTIR,       0, 2, -1 },
    { "lddr",   0xB8, amNA,       amNA,       LDDR,       0, 2, -1 },
    { "cpdr",   0xB9, amNA,       amNA,       CPDR,       0, 2, -1 },
    { "indr",   0xBA, amNA,       amNA,       INDR,       0, 2, -1 },
    { "otdr",   0xBB, amNA,       amNA,       OTDR,       0, 2, -1 },
  },
  { /* 0xCB codepage (4) */
    { "rlc",    0x00, amREGB,     amNA,       RLC,        0, 2, -1 },
    { "rlc",    0x01, amREGC,     amNA,       RLC,        0, 2, -1 },
    { "rlc",    0x02, amREGD,     amNA,       RLC,        0, 2, -1 },
    { "rlc",    0x03, amREGE,     amNA,       RLC,        0, 2, -1 },
    { "rlc",    0x04, amREGH,     amNA,       RLC,        0, 2, -1 },
    { "rlc",    0x05, amREGL,     amNA,       RLC,        0, 2, -1 },
    { "rlc",    0x06, amREGINDHL, amNA,       RLC,        0, 2, -1 },
    { "rlc",    0x07, amREGA,     amNA,       RLC,        0, 2, -1 },
    { "rrc",    0x08, amREGB,     amNA,       RRC,        0, 2, -1 },
    { "rrc",    0x09, amREGC,     amNA,       RRC,        0, 2, -1 },
    { "rrc",    0x0A, amREGD,     amNA,       RRC,        0, 2, -1 },
    { "rrc",    0x0B, amREGE,     amNA,       RRC,        0, 2, -1 },
    { "rrc",    0x0C, amREGH,     amNA,       RRC,        0, 2, -1 },
    { "rrc",    0x0D, amREGL,     amNA,       RRC,        0, 2, -1 },
    { "rrc",    0x0E, amREGINDHL, amNA,       RRC,        0, 2, -1 },
    { "rrc",    0x0F, amREGA,     amNA,       RRC,        0, 2, -1 },
    { "rl",     0x10, amREGB,     amNA,       RL,         0, 2, -1 },
    { "rl",     0x11, amREGC,     amNA,       RL,         0, 2, -1 },
    { "rl",     0x12, amREGD,     amNA,       RL,         0, 2, -1 },
    { "rl",     0x13, amREGE,     amNA,       RL,         0, 2, -1 },
    { "rl",     0x14, amREGH,     amNA,       RL,         0, 2, -1 },
    { "rl",     0x15, amREGL,     amNA,       RL,         0, 2, -1 },
    { "rl",     0x16, amREGINDHL, amNA,       RL,         0, 2, -1 },
    { "rl",     0x17, amREGA,     amNA,       RL,         0, 2, -1 },
    { "rr",     0x18, amREGB,     amNA,       RR,         0, 2, -1 },
    { "rr",     0x19, amREGC,     amNA,       RR,         0, 2, -1 },
    { "rr",     0x1A, amREGD,     amNA,       RR,         0, 2, -1 },
    { "rr",     0x1B, amREGE,     amNA,       RR,         0, 2, -1 },
    { "rr",     0x1C, amREGH,     amNA,       RR,         0, 2, -1 },
    { "rr",     0x1D, amREGL,     amNA,       RR,         0, 2, -1 },
    { "rr",     0x1E, amREGINDHL, amNA,       RR,         0, 2, -1 },
    { "rr",     0x1F, amREGA,     amNA,       RR,         0, 2, -1 },
    { "sla",    0x20, amREGB,     amNA,       SLA,        0, 2, -1 },
    { "sla",    0x21, amREGC,     amNA,       SLA,        0, 2, -1 },
    { "sla",    0x22, amREGD,     amNA,       SLA,        0, 2, -1 },
    { "sla",    0x23, amREGE,     amNA,       SLA,        0, 2, -1 },
    { "sla",    0x24, amREGH,     amNA,       SLA,        0, 2, -1 },
    { "sla",    0x25, amREGL,     amNA,       SLA,        0, 2, -1 },
    { "sla",    0x26, amREGINDHL, amNA,       SLA,        0, 2, -1 },
    { "sla",    0x27, amREGA,     amNA,       SLA,        0, 2, -1 },
    { "sra",    0x28, amREGB,     amNA,       SRA,        0, 2, -1 },
    { "sra",    0x29, amREGC,     amNA,       SRA,        0, 2, -1 },
    { "sra",    0x2A, amREGD,     amNA,       SRA,        0, 2, -1 },
    { "sra",    0x2B, amREGE,     amNA,       SRA,        0, 2, -1 },
    { "sra",    0x2C, amREGH,     amNA,       SRA,        0, 2, -1 },
    { "sra",    0x2D, amREGL,     amNA,       SRA,        0, 2, -1 },
    { "sra",    0x2E, amREGINDHL, amNA,       SRA,        0, 2, -1 },
    { "sra",    0x2F, amREGA,     amNA,       SRA,        0, 2, -1 },
    { "srl",    0x38, amREGB,     amNA,       SRL,        0, 2, -1 },
    { "srl",    0x39, amREGC,     amNA,       SRL,        0, 2, -1 },
    { "srl",    0x3A, amREGD,     amNA,       SRL,        0, 2, -1 },
    { "srl",    0x3B, amREGE,     amNA,       SRL,        0, 2, -1 },
    { "srl",    0x3C, amREGH,     amNA,       SRL,        0, 2, -1 },
    { "srl",    0x3D, amREGL,     amNA,       SRL,        0, 2, -1 },
    { "srl",    0x3E, amREGINDHL, amNA,       SRL,        0, 2, -1 },
    { "srl",    0x3F, amREGA,     amNA,       SRL,        0, 2, -1 },
    { "bit 0,", 0x40, amREGB,     amNA,       BIT,        0, 2, -1 },
    { "bit 0,", 0x41, amREGC,     amNA,       BIT,        0, 2, -1 },
    { "bit 0,", 0x42, amREGD,     amNA,       BIT,        0, 2, -1 },
    { "bit 0,", 0x43, amREGE,     amNA,       BIT,        0, 2, -1 },
    { "bit 0,", 0x44, amREGH,     amNA,       BIT,        0, 2, -1 },
    { "bit 0,", 0x45, amREGL,     amNA,       BIT,        0, 2, -1 },
    { "bit 0,", 0x46, amREGINDHL, amNA,       BIT,        0, 2, -1 },
    { "bit 0,", 0x47, amREGA,     amNA,       BIT,        0, 2, -1 },
    { "bit 1,", 0x48, amREGB,     amNA,       BIT,        0, 2, -1 },
    { "bit 1,", 0x49, amREGC,     amNA,       BIT,        0, 2, -1 },
    { "bit 1,", 0x4A, amREGD,     amNA,       BIT,        0, 2, -1 },
    { "bit 1,", 0x4B, amREGE,     amNA,       BIT,        0, 2, -1 },
    { "bit 1,", 0x4C, amREGH,     amNA,       BIT,        0, 2, -1 },
    { "bit 1,", 0x4D, amREGL,     amNA,       BIT,        0, 2, -1 },
    { "bit 1,", 0x4E, amREGINDHL, amNA,       BIT,        0, 2, -1 },
    { "bit 1,", 0x4F, amREGA,     amNA,       BIT,        0, 2, -1 },
    { "bit 2,", 0x50, amREGB,     amNA,       BIT,        0, 2, -1 },
    { "bit 2,", 0x51, amREGC,     amNA,       BIT,        0, 2, -1 },
    { "bit 2,", 0x52, amREGD,     amNA,       BIT,        0, 2, -1 },
    { "bit 2,", 0x53, amREGE,     amNA,       BIT,        0, 2, -1 },
    { "bit 2,", 0x54, amREGH,     amNA,       BIT,        0, 2, -1 },
    { "bit 2,", 0x55, amREGL,     amNA,       BIT,        0, 2, -1 },
    { "bit 2,", 0x56, amREGINDHL, amNA,       BIT,        0, 2, -1 },
    { "bit 2,", 0x57, amREGA,     amNA,       BIT,        0, 2, -1 },
    { "bit 3,", 0x58, amREGB,     amNA,       BIT,        0, 2, -1 },
    { "bit 3,", 0x59, amREGC,     amNA,       BIT,        0, 2, -1 },
    { "bit 3,", 0x5A, amREGD,     amNA,       BIT,        0, 2, -1 },
    { "bit 3,", 0x5B, amREGE,     amNA,       BIT,        0, 2, -1 },
    { "bit 3,", 0x5C, amREGH,     amNA,       BIT,        0, 2, -1 },
    { "bit 3,", 0x5D, amREGL,     amNA,       BIT,        0, 2, -1 },
    { "bit 3,", 0x5E, amREGINDHL, amNA,       BIT,        0, 2, -1 },
    { "bit 3,", 0x5F, amREGA,     amNA,       BIT,        0, 2, -1 },
    { "bit 4,", 0x60, amREGB,     amNA,       BIT,        0, 2, -1 },
    { "bit 4,", 0x61, amREGC,     amNA,       BIT,        0, 2, -1 },
    { "bit 4,", 0x62, amREGD,     amNA,       BIT,        0, 2, -1 },
    { "bit 4,", 0x63, amREGE,     amNA,       BIT,        0, 2, -1 },
    { "bit 4,", 0x64, amREGH,     amNA,       BIT,        0, 2, -1 },
    { "bit 4,", 0x65, amREGL,     amNA,       BIT,        0, 2, -1 },
    { "bit 4,", 0x66, amREGINDHL, amNA,       BIT,        0, 2, -1 },
    { "bit 4,", 0x67, amREGA,     amNA,       BIT,        0, 2, -1 },
    { "bit 5,", 0x68, amREGB,     amNA,       BIT,        0, 2, -1 },
    { "bit 5,", 0x69, amREGC,     amNA,       BIT,        0, 2, -1 },
    { "bit 5,", 0x6A, amREGD,     amNA,       BIT,        0, 2, -1 },
    { "bit 5,", 0x6B, amREGE,     amNA,       BIT,        0, 2, -1 },
    { "bit 5,", 0x6C, amREGH,     amNA,       BIT,        0, 2, -1 },
    { "bit 5,", 0x6D, amREGL,     amNA,       BIT,        0, 2, -1 },
    { "bit 5,", 0x6E, amREGINDHL, amNA,       BIT,        0, 2, -1 },
    { "bit 5,", 0x6F, amREGA,     amNA,       BIT,        0, 2, -1 },
    { "bit 6,", 0x70, amREGB,     amNA,       BIT,        0, 2, -1 },
    { "bit 6,", 0x71, amREGC,     amNA,       BIT,        0, 2, -1 },
    { "bit 6,", 0x72, amREGD,     amNA,       BIT,        0, 2, -1 },
    { "bit 6,", 0x73, amREGE,     amNA,       BIT,        0, 2, -1 },
    { "bit 6,", 0x74, amREGH,     amNA,       BIT,        0, 2, -1 },
    { "bit 6,", 0x75, amREGL,     amNA,       BIT,        0, 2, -1 },
    { "bit 6,", 0x76, amREGINDHL, amNA,       BIT,        0, 2, -1 },
    { "bit 6,", 0x77, amREGA,     amNA,       BIT,        0, 2, -1 },
    { "bit 7,", 0x78, amREGB,     amNA,       BIT,        0, 2, -1 },
    { "bit 7,", 0x79, amREGC,     amNA,       BIT,        0, 2, -1 },
    { "bit 7,", 0x7A, amREGD,     amNA,       BIT,        0, 2, -1 },
    { "bit 7,", 0x7B, amREGE,     amNA,       BIT,        0, 2, -1 },
    { "bit 7,", 0x7C, amREGH,     amNA,       BIT,        0, 2, -1 },
    { "bit 7,", 0x7D, amREGL,     amNA,       BIT,        0, 2, -1 },
    { "bit 7,", 0x7E, amREGINDHL, amNA,       BIT,        0, 2, -1 },
    { "bit 7,", 0x7F, amREGA,     amNA,       BIT,        0, 2, -1 },
    { "res 0,", 0x80, amREGB,     amNA,       RES,        0, 2, -1 },
    { "res 0,", 0x81, amREGC,     amNA,       RES,        0, 2, -1 },
    { "res 0,", 0x82, amREGD,     amNA,       RES,        0, 2, -1 },
    { "res 0,", 0x83, amREGE,     amNA,       RES,        0, 2, -1 },
    { "res 0,", 0x84, amREGH,     amNA,       RES,        0, 2, -1 },
    { "res 0,", 0x85, amREGL,     amNA,       RES,        0, 2, -1 },
    { "res 0,", 0x86, amREGINDHL, amNA,       RES,        0, 2, -1 },
    { "res 0,", 0x87, amREGA,     amNA,       RES,        0, 2, -1 },
    { "res 1,", 0x88, amREGB,     amNA,       RES,        0, 2, -1 },
    { "res 1,", 0x89, amREGC,     amNA,       RES,        0, 2, -1 },
    { "res 1,", 0x8A, amREGD,     amNA,       RES,        0, 2, -1 },
    { "res 1,", 0x8B, amREGE,     amNA,       RES,        0, 2, -1 },
    { "res 1,", 0x8C, amREGH,     amNA,       RES,        0, 2, -1 },
    { "res 1,", 0x8D, amREGL,     amNA,       RES,        0, 2, -1 },
    { "res 1,", 0x8E, amREGINDHL, amNA,       RES,        0, 2, -1 },
    { "res 1,", 0x8F, amREGA,     amNA,       RES,        0, 2, -1 },
    { "res 2,", 0x90, amREGB,     amNA,       RES,        0, 2, -1 },
    { "res 2,", 0x91, amREGC,     amNA,       RES,        0, 2, -1 },
    { "res 2,", 0x92, amREGD,     amNA,       RES,        0, 2, -1 },
    { "res 2,", 0x93, amREGE,     amNA,       RES,        0, 2, -1 },
    { "res 2,", 0x94, amREGH,     amNA,       RES,        0, 2, -1 },
    { "res 2,", 0x95, amREGL,     amNA,       RES,        0, 2, -1 },
    { "res 2,", 0x96, amREGINDHL, amNA,       RES,        0, 2, -1 },
    { "res 2,", 0x97, amREGA,     amNA,       RES,        0, 2, -1 },
    { "res 3,", 0x98, amREGB,     amNA,       RES,        0, 2, -1 },
    { "res 3,", 0x99, amREGC,     amNA,       RES,        0, 2, -1 },
    { "res 3,", 0x9A, amREGD,     amNA,       RES,        0, 2, -1 },
    { "res 3,", 0x9B, amREGE,     amNA,       RES,        0, 2, -1 },
    { "res 3,", 0x9C, amREGH,     amNA,       RES,        0, 2, -1 },
    { "res 3,", 0x9D, amREGL,     amNA,       RES,        0, 2, -1 },
    { "res 3,", 0x9E, amREGINDHL, amNA,       RES,        0, 2, -1 },
    { "res 3,", 0x9F, amREGA,     amNA,       RES,        0, 2, -1 },
    { "res 4,", 0xA0, amREGB,     amNA,       RES,        0, 2, -1 },
    { "res 4,", 0xA1, amREGC,     amNA,       RES,        0, 2, -1 },
    { "res 4,", 0xA2, amREGD,     amNA,       RES,        0, 2, -1 },
    { "res 4,", 0xA3, amREGE,     amNA,       RES,        0, 2, -1 },
    { "res 4,", 0xA4, amREGH,     amNA,       RES,        0, 2, -1 },
    { "res 4,", 0xA5, amREGL,     amNA,       RES,        0, 2, -1 },
    { "res 4,", 0xA6, amREGINDHL, amNA,       RES,        0, 2, -1 },
    { "res 4,", 0xA7, amREGA,     amNA,       RES,        0, 2, -1 },
    { "res 5,", 0xA8, amREGB,     amNA,       RES,        0, 2, -1 },
    { "res 5,", 0xA9, amREGC,     amNA,       RES,        0, 2, -1 },
    { "res 5,", 0xAA, amREGD,     amNA,       RES,        0, 2, -1 },
    { "res 5,", 0xAB, amREGE,     amNA,       RES,        0, 2, -1 },
    { "res 5,", 0xAC, amREGH,     amNA,       RES,        0, 2, -1 },
    { "res 5,", 0xAD, amREGL,     amNA,       RES,        0, 2, -1 },
    { "res 5,", 0xAE, amREGINDHL, amNA,       RES,        0, 2, -1 },
    { "res 5,", 0xAF, amREGA,     amNA,       RES,        0, 2, -1 },
    { "res 6,", 0xB0, amREGB,     amNA,       RES,        0, 2, -1 },
    { "res 6,", 0xB1, amREGC,     amNA,       RES,        0, 2, -1 },
    { "res 6,", 0xB2, amREGD,     amNA,       RES,        0, 2, -1 },
    { "res 6,", 0xB3, amREGE,     amNA,       RES,        0, 2, -1 },
    { "res 6,", 0xB4, amREGH,     amNA,       RES,        0, 2, -1 },
    { "res 6,", 0xB5, amREGL,     amNA,       RES,        0, 2, -1 },
    { "res 6,", 0xB6, amREGINDHL, amNA,       RES,        0, 2, -1 },
    { "res 6,", 0xB7, amREGA,     amNA,       RES,        0, 2, -1 },
    { "res 7,", 0xB8, amREGB,     amNA,       RES,        0, 2, -1 },
    { "res 7,", 0xB9, amREGC,     amNA,       RES,        0, 2, -1 },
    { "res 7,", 0xBA, amREGD,     amNA,       RES,        0, 2, -1 },
    { "res 7,", 0xBB, amREGE,     amNA,       RES,        0, 2, -1 },
    { "res 7,", 0xBC, amREGH,     amNA,       RES,        0, 2, -1 },
    { "res 7,", 0xBD, amREGL,     amNA,       RES,        0, 2, -1 },
    { "res 7,", 0xBE, amREGINDHL, amNA,       RES,        0, 2, -1 },
    { "res 7,", 0xBF, amREGA,     amNA,       RES,        0, 2, -1 },
    { "set 0,", 0xC0, amREGB,     amNA,       SET,        0, 2, -1 },
    { "set 0,", 0xC1, amREGC,     amNA,       SET,        0, 2, -1 },
    { "set 0,", 0xC2, amREGD,     amNA,       SET,        0, 2, -1 },
    { "set 0,", 0xC3, amREGE,     amNA,       SET,        0, 2, -1 },
    { "set 0,", 0xC4, amREGH,     amNA,       SET,        0, 2, -1 },
    { "set 0,", 0xC5, amREGL,     amNA,       SET,        0, 2, -1 },
    { "set 0,", 0xC6, amREGINDHL, amNA,       SET,        0, 2, -1 },
    { "set 0,", 0xC7, amREGA,     amNA,       SET,        0, 2, -1 },
    { "set 1,", 0xC8, amREGB,     amNA,       SET,        0, 2, -1 },
    { "set 1,", 0xC9, amREGC,     amNA,       SET,        0, 2, -1 },
    { "set 1,", 0xCA, amREGD,     amNA,       SET,        0, 2, -1 },
    { "set 1,", 0xCB, amREGE,     amNA,       SET,        0, 2, -1 },
    { "set 1,", 0xCC, amREGH,     amNA,       SET,        0, 2, -1 },
    { "set 1,", 0xCD, amREGL,     amNA,       SET,        0, 2, -1 },
    { "set 1,", 0xCE, amREGINDHL, amNA,       SET,        0, 2, -1 },
    { "set 1,", 0xCF, amREGA,     amNA,       SET,        0, 2, -1 },
    { "set 2,", 0xD0, amREGB,     amNA,       SET,        0, 2, -1 },
    { "set 2,", 0xD1, amREGC,     amNA,       SET,        0, 2, -1 },
    { "set 2,", 0xD2, amREGD,     amNA,       SET,        0, 2, -1 },
    { "set 2,", 0xD3, amREGE,     amNA,       SET,        0, 2, -1 },
    { "set 2,", 0xD4, amREGH,     amNA,       SET,        0, 2, -1 },
    { "set 2,", 0xD5, amREGL,     amNA,       SET,        0, 2, -1 },
    { "set 2,", 0xD6, amREGINDHL, amNA,       SET,        0, 2, -1 },
    { "set 2,", 0xD7, amREGA,     amNA,       SET,        0, 2, -1 },
    { "set 3,", 0xD8, amREGB,     amNA,       SET,        0, 2, -1 },
    { "set 3,", 0xD9, amREGC,     amNA,       SET,        0, 2, -1 },
    { "set 3,", 0xDA, amREGD,     amNA,       SET,        0, 2, -1 },
    { "set 3,", 0xDB, amREGE,     amNA,       SET,        0, 2, -1 },
    { "set 3,", 0xDC, amREGH,     amNA,       SET,        0, 2, -1 },
    { "set 3,", 0xDD, amREGL,     amNA,       SET,        0, 2, -1 },
    { "set 3,", 0xDE, amREGINDHL, amNA,       SET,        0, 2, -1 },
    { "set 3,", 0xDF, amREGA,     amNA,       SET,        0, 2, -1 },
    { "set 4,", 0xE0, amREGB,     amNA,       SET,        0, 2, -1 },
    { "set 4,", 0xE1, amREGC,     amNA,       SET,        0, 2, -1 },
    { "set 4,", 0xE2, amREGD,     amNA,       SET,        0, 2, -1 },
    { "set 4,", 0xE3, amREGE,     amNA,       SET,        0, 2, -1 },
    { "set 4,", 0xE4, amREGH,     amNA,       SET,        0, 2, -1 },
    { "set 4,", 0xE5, amREGL,     amNA,       SET,        0, 2, -1 },
    { "set 4,", 0xE6, amREGINDHL, amNA,       SET,        0, 2, -1 },
    { "set 4,", 0xE7, amREGA,     amNA,       SET,        0, 2, -1 },
    { "set 5,", 0xE8, amREGB,     amNA,       SET,        0, 2, -1 },
    { "set 5,", 0xE9, amREGC,     amNA,       SET,        0, 2, -1 },
    { "set 5,", 0xEA, amREGD,     amNA,       SET,        0, 2, -1 },
    { "set 5,", 0xEB, amREGE,     amNA,       SET,        0, 2, -1 },
    { "set 5,", 0xEC, amREGH,     amNA,       SET,        0, 2, -1 },
    { "set 5,", 0xED, amREGL,     amNA,       SET,        0, 2, -1 },
    { "set 5,", 0xEE, amREGINDHL, amNA,       SET,        0, 2, -1 },
    { "set 5,", 0xEF, amREGA,     amNA,       SET,        0, 2, -1 },
    { "set 6,", 0xF0, amREGB,     amNA,       SET,        0, 2, -1 },
    { "set 6,", 0xF1, amREGC,     amNA,       SET,        0, 2, -1 },
    { "set 6,", 0xF2, amREGD,     amNA,       SET,        0, 2, -1 },
    { "set 6,", 0xF3, amREGE,     amNA,       SET,        0, 2, -1 },
    { "set 6,", 0xF4, amREGH,     amNA,       SET,        0, 2, -1 },
    { "set 6,", 0xF5, amREGL,     amNA,       SET,        0, 2, -1 },
    { "set 6,", 0xF6, amREGINDHL, amNA,       SET,        0, 2, -1 },
    { "set 6,", 0xF7, amREGA,     amNA,       SET,        0, 2, -1 },
    { "set 7,", 0xF8, amREGB,     amNA,       SET,        0, 2, -1 },
    { "set 7,", 0xF9, amREGC,     amNA,       SET,        0, 2, -1 },
    { "set 7,", 0xFA, amREGD,     amNA,       SET,        0, 2, -1 },
    { "set 7,", 0xFB, amREGE,     amNA,       SET,        0, 2, -1 },
    { "set 7,", 0xFC, amREGH,     amNA,       SET,        0, 2, -1 },
    { "set 7,", 0xFD, amREGL,     amNA,       SET,        0, 2, -1 },
    { "set 7,", 0xFE, amREGINDHL, amNA,       SET,        0, 2, -1 },
    { "set 7,", 0xFF, amREGA,     amNA,       SET,        0, 2, -1 },
  },
};
#endif