#ifndef z80opcodesH
#define z80opcodesH

// ready for 8-bit arithmetic group

enum ADDRESSINGMODE {
  amNONE = 0,
  amREGB,
  amREGC,
  amREGD,
  amREGE,
  amREGH,
  amREGL,
  amREGA,
  amREGI,
  amREGR,
  amREGAF,
  amREGAFALT,
  amREGBC,
  amREGDE,
  amREGHL,
  amREGSP,
  amREGIX,
  amREGIY,
  amREGINDIRECT,        // (HL) for CB, (IX+n) for DDCB, (IY+n) for FDCB
  amINDBC,              // (BC)
  amINDDE,              // (DE)
  amINDHL,              // (HL)
  amINDSP,              // (SP)
  amINDIX,              // (IX)
  amINDIY,              // (IY)
  amINDEXX,
  amINDEXY,
  amEXTENDED,
  amIMMEDIATE,
  amIMMEDEX,
  amIOPORT,
  amIOPORTC,
  amRELATIVE,
  amCODEPAGE,           // If this is the addressing mode, the mnemonic member is actually a pointer to the next codepage
};

typedef struct {
  unsigned char opcode;
  char *mnemonic;
  enum ADDRESSINGMODE am1;
  enum ADDRESSINGMODE am2;
  int size;             // instruction size in bytes (including parameters)
} OPCODE;

OPCODE CBcodepage[];
OPCODE DDcodepage[];
OPCODE EDcodepage[];
OPCODE FDcodepage[];
OPCODE z80codepage[] = {
  { 0x00, "nop",        amNONE,         amNONE,         1 },
  { 0x01, "ld",         amREGBC,        amIMMEDEX,      3 },
  { 0x02, "ld",         amINDBC,        amREGA,         1 },
  { 0x03, "inc",        amREGBC,        amNONE,         1 },
  { 0x04, "inc",        amREGB,         amNONE,         1 },
  { 0x05, "dec",        amREGB,         amNONE,         1 },
  { 0x06, "ld",         amREGB,         amIMMEDIATE,    2 },
  { 0x07, "rlca",       amNONE,         amNONE,         1 },
  { 0x08, "ex",         amREGAF,        amREGAFALT,     1 },
  { 0x09, "add",        amREGHL,        amREGBC,        1 },
  { 0x0a, "ld",         amREGA,         amINDBC,        1 },
  { 0x0b, "dec",        amREGBC,        amNONE,         1 },
  { 0x0c, "inc",        amREGC,         amNONE,         1 },
  { 0x0d, "dec",        amREGC,         amNONE,         1 },
  { 0x0e, "ld",         amREGC,         amIMMEDIATE,    2 },
  { 0x0f, "rrca",       amNONE,         amNONE,         1 },
  { 0x10, "djnz",       amRELATIVE,     amNONE,         2 },
  { 0x11, "ld",         amREGDE,        amIMMEDEX,      3 },
  { 0x12, "ld",         amINDDE,        amREGA,         1 },
  { 0x13, "inc",        amREGDE,        amNONE,         1 },
  { 0x14, "inc",        amREGD,         amNONE,         1 },
  { 0x15, "dec",        amREGD,         amNONE,         1 },
  { 0x16, "ld",         amREGD,         amIMMEDIATE,    2 },
  { 0x17, "rla",        amNONE,         amNONE,         1 },
  { 0x18, "jr",         amRELATIVE,     amNONE,         2 },
  { 0x19, "add",        amREGHL,        amREGDE,        1 },
  { 0x1a, "ld",         amREGA,         amINDDE,        1 },
  { 0x1b, "dec",        amREGDE,        amNONE,         1 },
  { 0x1c, "inc",        amREGE,         amNONE,         1 },
  { 0x1d, "dec",        amREGE,         amNONE,         1 },
  { 0x1e, "ld",         amREGE,         amIMMEDIATE,    2 },
  { 0x1f, "rra",        amNONE,         amNONE,         1 },
  { 0x20, "jr nz,",     amRELATIVE,     amNONE,         2 },
  { 0x21, "ld",         amREGHL,        amIMMEDEX,      3 },
  { 0x22, "ld",         amEXTENDED,     amREGHL,        3 },
  { 0x23, "inc",        amREGHL,        amNONE,         1 },
  { 0x24, "inc",        amREGH,         amNONE,         1 },
  { 0x25, "dec",        amREGH,         amNONE,         1 },
  { 0x26, "ld",         amREGH,         amIMMEDIATE,    2 },
  { 0x27, "daa",        amNONE,         amNONE,         1 },
  { 0x28, "jr z,",      amRELATIVE,     amNONE,         2 },
  { 0x29, "add",        amREGHL,        amREGHL,        1 },
  { 0x2a, "ld",         amREGHL,        amEXTENDED,     3 },
  { 0x2b, "dec",        amREGHL,        amNONE,         1 },
  { 0x2c, "inc",        amREGL,         amNONE,         1 },
  { 0x2d, "dec",        amREGL,         amNONE,         1 },
  { 0x2e, "ld",         amREGL,         amIMMEDIATE,    2 },
  { 0x2f, "cpl",        amNONE,         amNONE,         1 },
  { 0x30, "jr nc,",     amRELATIVE,     amNONE,         2 },
  { 0x31, "ld",         amREGSP,        amIMMEDEX,      3 },
  { 0x32, "ld",         amEXTENDED,     amREGA,         3 },
  { 0x33, "inc",        amREGSP,        amNONE,         1 },
  { 0x34, "inc",        amINDHL,        amNONE,         1 },
  { 0x35, "dec",        amINDHL,        amNONE,         1 },
  { 0x36, "ld",         amINDHL,        amIMMEDIATE,    2 },
  { 0x37, "scf",        amNONE,         amNONE,         1 },
  { 0x38, "jr c,",      amRELATIVE,     amNONE,         2 },
  { 0x39, "add",        amREGHL,        amREGSP,        1 },
  { 0x3a, "ld",         amREGA,         amEXTENDED,     3 },
  { 0x3b, "dec",        amREGSP,        amNONE,         1 },
  { 0x3c, "inc",        amREGA,         amNONE,         1 },
  { 0x3d, "dec",        amREGA,         amNONE,         1 },
  { 0x3e, "ld",         amREGA,         amIMMEDIATE,    2 },
  { 0x3f, "ccf",        amNONE,         amNONE,         1 },
  { 0x40, "ld",         amREGB,         amREGB,         1 },
  { 0x41, "ld",         amREGB,         amREGC,         1 },
  { 0x42, "ld",         amREGB,         amREGD,         1 },
  { 0x43, "ld",         amREGB,         amREGE,         1 },
  { 0x44, "ld",         amREGB,         amREGH,         1 },
  { 0x45, "ld",         amREGB,         amREGL,         1 },
  { 0x46, "ld",         amREGB,         amINDHL,        1 },
  { 0x47, "ld",         amREGB,         amREGA,         1 },
  { 0x48, "ld",         amREGC,         amREGB,         1 },
  { 0x49, "ld",         amREGC,         amREGC,         1 },
  { 0x4a, "ld",         amREGC,         amREGD,         1 },
  { 0x4b, "ld",         amREGC,         amREGE,         1 },
  { 0x4c, "ld",         amREGC,         amREGH,         1 },
  { 0x4d, "ld",         amREGC,         amREGL,         1 },
  { 0x4e, "ld",         amREGC,         amINDHL,        1 },
  { 0x4f, "ld",         amREGC,         amREGA,         1 },
  { 0x50, "ld",         amREGD,         amREGB,         1 },
  { 0x51, "ld",         amREGD,         amREGC,         1 },
  { 0x52, "ld",         amREGD,         amREGD,         1 },
  { 0x53, "ld",         amREGD,         amREGE,         1 },
  { 0x54, "ld",         amREGD,         amREGH,         1 },
  { 0x55, "ld",         amREGD,         amREGL,         1 },
  { 0x56, "ld",         amREGD,         amINDHL,        1 },
  { 0x57, "ld",         amREGD,         amREGA,         1 },
  { 0x58, "ld",         amREGE,         amREGB,         1 },
  { 0x59, "ld",         amREGE,         amREGC,         1 },
  { 0x5a, "ld",         amREGE,         amREGD,         1 },
  { 0x5b, "ld",         amREGE,         amREGE,         1 },
  { 0x5c, "ld",         amREGE,         amREGH,         1 },
  { 0x5d, "ld",         amREGE,         amREGL,         1 },
  { 0x5e, "ld",         amREGE,         amINDHL,        1 },
  { 0x5f, "ld",         amREGE,         amREGA,         1 },
  { 0x60, "ld",         amREGH,         amREGB,         1 },
  { 0x61, "ld",         amREGH,         amREGC,         1 },
  { 0x62, "ld",         amREGH,         amREGD,         1 },
  { 0x63, "ld",         amREGH,         amREGE,         1 },
  { 0x64, "ld",         amREGH,         amREGH,         1 },
  { 0x65, "ld",         amREGH,         amREGL,         1 },
  { 0x66, "ld",         amREGH,         amINDHL,        1 },
  { 0x67, "ld",         amREGH,         amREGA,         1 },
  { 0x68, "ld",         amREGL,         amREGB,         1 },
  { 0x69, "ld",         amREGL,         amREGC,         1 },
  { 0x6a, "ld",         amREGL,         amREGD,         1 },
  { 0x6b, "ld",         amREGL,         amREGE,         1 },
  { 0x6c, "ld",         amREGL,         amREGH,         1 },
  { 0x6d, "ld",         amREGL,         amREGL,         1 },
  { 0x6e, "ld",         amREGL,         amINDHL,        1 },
  { 0x6f, "ld",         amREGL,         amREGA,         1 },
  { 0x70, "ld",         amINDHL,        amREGB,         1 },
  { 0x71, "ld",         amINDHL,        amREGC,         1 },
  { 0x72, "ld",         amINDHL,        amREGD,         1 },
  { 0x73, "ld",         amINDHL,        amREGE,         1 },
  { 0x74, "ld",         amINDHL,        amREGH,         1 },
  { 0x75, "ld",         amINDHL,        amREGL,         1 },
  { 0x76, "halt",       amNONE,         amNONE,         1 },
  { 0x77, "ld",         amINDHL,        amREGA,         1 },
  { 0x78, "ld",         amREGA,         amREGB,         1 },
  { 0x79, "ld",         amREGA,         amREGC,         1 },
  { 0x7a, "ld",         amREGA,         amREGD,         1 },
  { 0x7b, "ld",         amREGA,         amREGE,         1 },
  { 0x7c, "ld",         amREGA,         amREGH,         1 },
  { 0x7d, "ld",         amREGA,         amREGL,         1 },
  { 0x7e, "ld",         amREGA,         amINDHL,        1 },
  { 0x7f, "ld",         amREGA,         amREGA,         1 },
  { 0x80, "add",        amREGA,         amREGB,         1 },
  { 0x81, "add",        amREGA,         amREGC,         1 },
  { 0x82, "add",        amREGA,         amREGD,         1 },
  { 0x83, "add",        amREGA,         amREGE,         1 },
  { 0x84, "add",        amREGA,         amREGH,         1 },
  { 0x85, "add",        amREGA,         amREGL,         1 },
  { 0x86, "add",        amREGA,         amINDHL,        1 },
  { 0x87, "add",        amREGA,         amREGA,         1 },
  { 0x88, "adc",        amREGA,         amREGB,         1 },
  { 0x89, "adc",        amREGA,         amREGC,         1 },
  { 0x8a, "adc",        amREGA,         amREGD,         1 },
  { 0x8b, "adc",        amREGA,         amREGE,         1 },
  { 0x8c, "adc",        amREGA,         amREGH,         1 },
  { 0x8d, "adc",        amREGA,         amREGL,         1 },
  { 0x8e, "adc",        amREGA,         amINDHL,        1 },
  { 0x8f, "adc",        amREGA,         amREGA,         1 },
  { 0x90, "sub",        amREGB,         amNONE,         1 },
  { 0x91, "sub",        amREGC,         amNONE,         1 },
  { 0x92, "sub",        amREGD,         amNONE,         1 },
  { 0x93, "sub",        amREGE,         amNONE,         1 },
  { 0x94, "sub",        amREGH,         amNONE,         1 },
  { 0x95, "sub",        amREGL,         amNONE,         1 },
  { 0x96, "sub",        amINDHL,        amNONE,         1 },
  { 0x97, "sub",        amREGA,         amNONE,         1 },
  { 0x98, "sbc",        amREGB,         amNONE,         1 },
  { 0x99, "sbc",        amREGC,         amNONE,         1 },
  { 0x9a, "sbc",        amREGD,         amNONE,         1 },
  { 0x9b, "sbc",        amREGE,         amNONE,         1 },
  { 0x9c, "sbc",        amREGH,         amNONE,         1 },
  { 0x9d, "sbc",        amREGL,         amNONE,         1 },
  { 0x9e, "sbc",        amINDHL,        amNONE,         1 },
  { 0x9f, "sbc",        amREGA,         amNONE,         1 },
  { 0xa0, "and",        amREGB,         amNONE,         1 },
  { 0xa1, "and",        amREGC,         amNONE,         1 },
  { 0xa2, "and",        amREGD,         amNONE,         1 },
  { 0xa3, "and",        amREGE,         amNONE,         1 },
  { 0xa4, "and",        amREGH,         amNONE,         1 },
  { 0xa5, "and",        amREGL,         amNONE,         1 },
  { 0xa6, "and",        amINDHL,        amNONE,         1 },
  { 0xa7, "and",        amREGA,         amNONE,         1 },
  { 0xa8, "xor",        amREGB,         amNONE,         1 },
  { 0xa9, "xor",        amREGC,         amNONE,         1 },
  { 0xaa, "xor",        amREGD,         amNONE,         1 },
  { 0xab, "xor",        amREGE,         amNONE,         1 },
  { 0xac, "xor",        amREGH,         amNONE,         1 },
  { 0xad, "xor",        amREGL,         amNONE,         1 },
  { 0xae, "xor",        amINDHL,        amNONE,         1 },
  { 0xaf, "xor",        amREGA,         amNONE,         1 },
  { 0xb0, "or",         amREGB,         amNONE,         1 },
  { 0xb1, "or",         amREGC,         amNONE,         1 },
  { 0xb2, "or",         amREGD,         amNONE,         1 },
  { 0xb3, "or",         amREGE,         amNONE,         1 },
  { 0xb4, "or",         amREGH,         amNONE,         1 },
  { 0xb5, "or",         amREGL,         amNONE,         1 },
  { 0xb6, "or",         amINDHL,        amNONE,         1 },
  { 0xb7, "or",         amREGA,         amNONE,         1 },
  { 0xb8, "cp",         amREGB,         amNONE,         1 },
  { 0xb9, "cp",         amREGC,         amNONE,         1 },
  { 0xba, "cp",         amREGD,         amNONE,         1 },
  { 0xbb, "cp",         amREGE,         amNONE,         1 },
  { 0xbc, "cp",         amREGH,         amNONE,         1 },
  { 0xbd, "cp",         amREGL,         amNONE,         1 },
  { 0xbe, "cp",         amINDHL,        amNONE,         1 },
  { 0xbf, "cp",         amREGA,         amNONE,         1 },
  { 0xc0, "ret nz",     amNONE,         amNONE,         1 },
  { 0xc1, "pop",        amREGBC,        amNONE,         1 },
  { 0xc2, "jp nz,",     amIMMEDEX,      amNONE,         3 },
  { 0xc3, "jp",         amIMMEDEX,      amNONE,         3 },
  { 0xc4, "call nz,",   amIMMEDEX,      amNONE,         3 },
  { 0xc5, "push",       amREGBC,        amNONE,         1 },
  { 0xc6, "add",        amREGA,         amIMMEDIATE,    2 },
  { 0xc7, "rst 0x00",   amNONE,         amNONE,         1 },
  { 0xc8, "ret z",      amNONE,         amNONE,         1 },
  { 0xc9, "ret",        amNONE,         amNONE,         1 },
  { 0xca, "jp z,",      amIMMEDEX,      amNONE,         3 },
  { 0xcb, (char*)CBcodepage, amCODEPAGE,amNONE,         1 },
  { 0xcc, "call z,",    amIMMEDEX,      amNONE,         3 },
  { 0xcd, "call",       amIMMEDEX,      amNONE,         3 },
  { 0xce, "adc",        amREGA,         amIMMEDIATE,    2 },
  { 0xcf, "rst 0x08",   amNONE,         amNONE,         1 },
  { 0xd0, "ret nc",     amNONE,         amNONE,         1 },
  { 0xd1, "pop",        amREGDE,        amNONE,         1 },
  { 0xd2, "jp nc,",     amIMMEDEX,      amNONE,         3 },
  { 0xd3, "out",        amIOPORT,       amREGA,         2 },
  { 0xd4, "call nc,",   amIMMEDEX,      amNONE,         3 },
  { 0xd5, "push",       amREGDE,        amNONE,         1 },
  { 0xd6, "sub",        amIMMEDIATE,    amNONE,         2 },
  { 0xd7, "rst 0x10",   amNONE,         amNONE,         1 },
  { 0xd8, "ret c",      amNONE,         amNONE,         1 },
  { 0xd9, "exx",        amNONE,         amNONE,         1 },
  { 0xda, "jp c,",      amIMMEDEX,      amNONE,         3 },
  { 0xdb, "in",         amREGA,         amIOPORT,       2 },
  { 0xdc, "call c,",    amIMMEDEX,      amNONE,         3 },
  { 0xdd, (char*)DDcodepage, amCODEPAGE,amNONE,         1 },
  { 0xde, "sbc",        amIMMEDIATE,    amNONE,         2 },
  { 0xdf, "rst 0x18",   amNONE,         amNONE,         1 },
  { 0xe0, "ret po",     amNONE,         amNONE,         1 },
  { 0xe1, "pop",        amREGHL,        amNONE,         1 },
  { 0xe2, "jp po,",     amIMMEDEX,      amNONE,         3 },
  { 0xe3, "ex",         amINDSP,        amREGHL,        1 },
  { 0xe4, "call po,",   amIMMEDEX,      amNONE,         3 },
  { 0xe5, "push",       amREGHL,        amNONE,         1 },
  { 0xe6, "and",        amIMMEDIATE,    amNONE,         2 },
  { 0xe7, "rst 0x20",   amNONE,         amNONE,         1 },
  { 0xe8, "ret pe",     amNONE,         amNONE,         1 },
  { 0xe9, "jp",         amINDHL,        amNONE,         1 },
  { 0xea, "jp pe,",     amIMMEDEX,      amNONE,         3 },
  { 0xeb, "ex",         amREGDE,        amREGHL,        1 },
  { 0xec, "call pe,",   amIMMEDEX,      amNONE,         3 },
  { 0xed, (char*)EDcodepage, amCODEPAGE,amNONE,         1 },
  { 0xee, "xor",        amIMMEDIATE,    amNONE,         2 },
  { 0xef, "rst 0x28",   amNONE,         amNONE,         1 },
  { 0xf0, "ret p",      amNONE,         amNONE,         1 },
  { 0xf1, "pop",        amREGAF,        amNONE,         1 },
  { 0xf2, "jp p,",      amIMMEDEX,      amNONE,         3 },
  { 0xf3, "di",         amNONE,         amNONE,         1 },
  { 0xf4, "call p,",    amIMMEDEX,      amNONE,         3 },
  { 0xf5, "push",       amREGAF,        amNONE,         1 },
  { 0xf6, "or",         amIMMEDIATE,    amNONE,         2 },
  { 0xf7, "rst 0x30",   amNONE,         amNONE,         1 },
  { 0xf8, "ret m",     amNONE,         amNONE,         1 },
  { 0xf9, "ld",         amREGSP,        amREGHL,        1 },
  { 0xfa, "jp m,",      amIMMEDEX,      amNONE,         3 },
  { 0xfb, "ei",         amNONE,         amNONE,         1 },
  { 0xfc, "call m,",    amIMMEDEX,      amNONE,         3 },
  { 0xfd, (char*)FDcodepage, amCODEPAGE,amNONE,         1 },
  { 0xfe, "cp",         amIMMEDIATE,    amNONE,         2 },
  { 0xff, "rst 0x38",   amNONE,         amNONE,         1 },
};

OPCODE DDcodepage[] = {
  { 0x09, "add",        amREGIX,        amREGBC,        1 },
  { 0x19, "add",        amREGIX,        amREGDE,        1 },
  { 0x21, "ld",         amREGIX,        amIMMEDEX,      3 },
  { 0x22, "ld",         amEXTENDED,     amREGIX,        3 },
  { 0x23, "inc",        amREGIX,        amNONE,         1 },
  { 0x29, "add",        amREGIX,        amREGIX,        1 },
  { 0x2a, "ld",         amREGIX,        amEXTENDED,     3 },
  { 0x2b, "dec",        amREGIX,        amNONE,         1 },
  { 0x34, "inc",        amINDEXX,       amNONE,         2 },
  { 0x35, "dec",        amINDEXX,       amNONE,         2 },
  { 0x36, "ld",         amINDEXX,       amIMMEDIATE,    3 },
  { 0x39, "add",        amREGIX,        amREGSP,        1 },
  { 0x46, "ld",         amREGB,         amINDEXX,       2 },
  { 0x4e, "ld",         amREGC,         amINDEXX,       2 },
  { 0x56, "ld",         amREGD,         amINDEXX,       2 },
  { 0x5e, "ld",         amREGE,         amINDEXX,       2 },
  { 0x66, "ld",         amREGH,         amINDEXX,       2 },
  { 0x6e, "ld",         amREGL,         amINDEXX,       2 },
  { 0x70, "ld",         amINDEXX,       amREGB,         2 },
  { 0x71, "ld",         amINDEXX,       amREGC,         2 },
  { 0x72, "ld",         amINDEXX,       amREGD,         2 },
  { 0x73, "ld",         amINDEXX,       amREGE,         2 },
  { 0x74, "ld",         amINDEXX,       amREGH,         2 },
  { 0x75, "ld",         amINDEXX,       amREGL,         2 },
  { 0x77, "ld",         amINDEXX,       amREGA,         2 },
  { 0x7e, "ld",         amREGA,         amINDEXX,       2 },
  { 0x86, "add",        amREGA,         amINDEXX,       2 },
  { 0x8e, "adc",        amREGA,         amINDEXX,       2 },
  { 0x96, "sub",        amINDEXX,       amNONE,         2 },
  { 0x9e, "sbc",        amINDEXX,       amNONE,         2 },
  { 0xa6, "and",        amINDEXX,       amNONE,         2 },
  { 0xae, "xor",        amINDEXX,       amNONE,         2 },
  { 0xb6, "or",         amINDEXX,       amNONE,         2 },
  { 0xbe, "cp",         amINDEXX,       amNONE,         2 },
  { 0xcb, (char*)CBcodepage, amCODEPAGE,amNONE,         2 },
  { 0xe1, "pop",        amREGIX,        amNONE,         1 },
  { 0xe3, "ex",         amINDSP,        amREGIX,        1 },
  { 0xe5, "push",       amREGIX,        amNONE,         1 },
  { 0xe9, "jp",         amINDIX,        amNONE,         1 },
  { 0xf9, "ld",         amREGSP,        amREGIX,        1 },
};

OPCODE FDcodepage[] = {
  { 0x09, "add",        amREGIY,        amREGBC,        1 },
  { 0x19, "add",        amREGIY,        amREGDE,        1 },
  { 0x21, "ld",         amREGIY,        amIMMEDEX,      3 },
  { 0x22, "ld",         amEXTENDED,     amREGIY,        3 },
  { 0x23, "inc",        amREGIY,        amNONE,         1 },
  { 0x29, "add",        amREGIY,        amREGIY,        1 },
  { 0x2a, "ld",         amREGIY,        amEXTENDED,     3 },
  { 0x2b, "dec",        amREGIY,        amNONE,         1 },
  { 0x34, "inc",        amINDEXY,       amNONE,         2 },
  { 0x35, "dec",        amINDEXY,       amNONE,         2 },
  { 0x36, "ld",         amINDEXY,       amIMMEDIATE,    3 },
  { 0x39, "add",        amREGIY,        amREGSP,        1 },
  { 0x46, "ld",         amREGB,         amINDEXY,       2 },
  { 0x4e, "ld",         amREGC,         amINDEXY,       2 },
  { 0x56, "ld",         amREGD,         amINDEXY,       2 },
  { 0x5e, "ld",         amREGE,         amINDEXY,       2 },
  { 0x66, "ld",         amREGH,         amINDEXY,       2 },
  { 0x6e, "ld",         amREGL,         amINDEXY,       2 },
  { 0x70, "ld",         amINDEXY,       amREGB,         2 },
  { 0x71, "ld",         amINDEXY,       amREGC,         2 },
  { 0x72, "ld",         amINDEXY,       amREGD,         2 },
  { 0x73, "ld",         amINDEXY,       amREGE,         2 },
  { 0x74, "ld",         amINDEXY,       amREGH,         2 },
  { 0x75, "ld",         amINDEXY,       amREGL,         2 },
  { 0x77, "ld",         amINDEXY,       amREGA,         2 },
  { 0x7e, "ld",         amREGA,         amINDEXY,       2 },
  { 0x86, "add",        amREGA,         amINDEXY,       2 },
  { 0x8e, "adc",        amREGA,         amINDEXY,       2 },
  { 0x96, "sub",        amINDEXY,       amNONE,         2 },
  { 0x9e, "sbc",        amINDEXY,       amNONE,         2 },
  { 0xa6, "and",        amINDEXY,       amNONE,         2 },
  { 0xae, "xor",        amINDEXY,       amNONE,         2 },
  { 0xb6, "or",         amINDEXY,       amNONE,         2 },
  { 0xbe, "cp",         amINDEXY,       amNONE,         2 },
  { 0xcb, (char*)CBcodepage, amCODEPAGE,amNONE,         2 },
  { 0xe1, "pop",        amREGIY,        amNONE,         1 },
  { 0xe3, "ex",         amINDSP,        amREGIY,        1 },
  { 0xe5, "push",       amREGIY,        amNONE,         1 },
  { 0xe9, "jp",         amINDIY,        amNONE,         1 },
  { 0xf9, "ld",         amREGSP,        amREGIY,        1 },
};

OPCODE EDcodepage[] = {
  { 0x40, "in",         amREGB,         amIOPORTC,      1 },
  { 0x41, "out",        amIOPORTC,      amREGB,         1 },
  { 0x42, "sbc",        amREGHL,        amREGBC,        1 },
  { 0x43, "ld",         amEXTENDED,     amREGBC,        3 },
  { 0x44, "neg",        amNONE,         amNONE,         1 },
  { 0x45, "retn",       amNONE,         amNONE,         1 },
  { 0x46, "im 0",       amNONE,         amNONE,         1 },
  { 0x47, "ld",         amREGI,         amREGA,         1 },
  { 0x48, "in",         amREGC,         amIOPORTC,      1 },
  { 0x49, "out",        amIOPORTC,      amREGC,         1 },
  { 0x4a, "adc",        amREGHL,        amREGBC,        1 },
  { 0x4b, "ld",         amREGBC,        amEXTENDED,     3 },
  { 0x4d, "reti",       amNONE,         amNONE,         1 },
  { 0x4f, "ld",         amREGR,         amREGA,         1 },
  { 0x50, "in",         amREGD,         amIOPORTC,      1 },
  { 0x51, "out",        amIOPORTC,      amREGD,         1 },
  { 0x52, "sbc",        amREGHL,        amREGDE,        1 },
  { 0x53, "ld",         amEXTENDED,     amREGDE,        3 },
  { 0x56, "im 1",       amNONE,         amNONE,         1 },
  { 0x57, "ld",         amREGA,         amREGI,         1 },
  { 0x58, "in",         amREGE,         amIOPORTC,      1 },
  { 0x59, "out",        amIOPORTC,      amREGE,         1 },
  { 0x5a, "adc",        amREGHL,        amREGDE,        1 },
  { 0x5b, "ld",         amREGDE,        amEXTENDED,     3 },
  { 0x5e, "im 2",       amNONE,         amNONE,         1 },
  { 0x5f, "ld",         amREGA,         amREGR,         1 },
  { 0x60, "in",         amREGH,         amIOPORTC,      1 },
  { 0x61, "out",        amIOPORTC,      amREGH,         1 },
  { 0x62, "sbc",        amREGHL,        amREGHL,        1 },
  { 0x63, "ld",         amEXTENDED,     amREGHL,        3 },
  { 0x67, "rrd",        amNONE,         amNONE,         1 },
  { 0x68, "in",         amREGL,         amIOPORTC,      1 },
  { 0x69, "out",        amIOPORTC,      amREGL,         1 },
  { 0x6a, "adc",        amREGHL,        amREGHL,        1 },
  { 0x6b, "ld",         amREGHL,        amEXTENDED,     3 },
  { 0x6f, "rld",        amNONE,         amNONE,         1 },
  { 0x72, "sbc",        amREGHL,        amREGSP,        1 },
  { 0x73, "ld",         amEXTENDED,     amREGSP,        3 },
  { 0x78, "in",         amREGA,         amIOPORTC,      1 },
  { 0x79, "out",        amIOPORTC,      amREGA,         1 },
  { 0x7a, "adc",        amREGHL,        amREGSP,        1 },
  { 0x7b, "ld",         amREGSP,        amEXTENDED,     3 },
  { 0xa0, "ldi",        amNONE,         amNONE,         1 },
  { 0xa1, "cpi",        amNONE,         amNONE,         1 },
  { 0xa2, "ini",        amNONE,         amNONE,         1 },
  { 0xa3, "outi",       amNONE,         amNONE,         1 },
  { 0xa8, "ldd",        amNONE,         amNONE,         1 },
  { 0xa9, "cpd",        amNONE,         amNONE,         1 },
  { 0xaa, "ind",        amNONE,         amNONE,         1 },
  { 0xab, "outd",       amNONE,         amNONE,         1 },
  { 0xb0, "ldir",       amNONE,         amNONE,         1 },
  { 0xb1, "cpir",       amNONE,         amNONE,         1 },
  { 0xb2, "inir",       amNONE,         amNONE,         1 },
  { 0xb3, "otir",       amNONE,         amNONE,         1 },
  { 0xb8, "lddr",       amNONE,         amNONE,         1 },
  { 0xb9, "cpdr",       amNONE,         amNONE,         1 },
  { 0xba, "indr",       amNONE,         amNONE,         1 },
  { 0xbb, "otdr",       amNONE,         amNONE,         1 },
};

OPCODE CBcodepage[] = {
  { 0x00, "rlc",        amREGB,         amNONE,         1 },
  { 0x01, "rlc",        amREGC,         amNONE,         1 },
  { 0x02, "rlc",        amREGD,         amNONE,         1 },
  { 0x03, "rlc",        amREGE,         amNONE,         1 },
  { 0x04, "rlc",        amREGH,         amNONE,         1 },
  { 0x05, "rlc",        amREGL,         amNONE,         1 },
  { 0x06, "rlc",        amREGINDIRECT,  amNONE,         1 },
  { 0x07, "rlc",        amREGA,         amNONE,         1 },
  { 0x08, "rrc",        amREGB,         amNONE,         1 },
  { 0x09, "rrc",        amREGC,         amNONE,         1 },
  { 0x0a, "rrc",        amREGD,         amNONE,         1 },
  { 0x0b, "rrc",        amREGE,         amNONE,         1 },
  { 0x0c, "rrc",        amREGH,         amNONE,         1 },
  { 0x0d, "rrc",        amREGL,         amNONE,         1 },
  { 0x0e, "rrc",        amREGINDIRECT,  amNONE,         1 },
  { 0x0f, "rrc",        amREGA,         amNONE,         1 },
  { 0x10, "rl",         amREGB,         amNONE,         1 },
  { 0x11, "rl",         amREGC,         amNONE,         1 },
  { 0x12, "rl",         amREGD,         amNONE,         1 },
  { 0x13, "rl",         amREGE,         amNONE,         1 },
  { 0x14, "rl",         amREGH,         amNONE,         1 },
  { 0x15, "rl",         amREGL,         amNONE,         1 },
  { 0x16, "rl",         amREGINDIRECT,  amNONE,         1 },
  { 0x17, "rl",         amREGA,         amNONE,         1 },
  { 0x18, "rr",         amREGB,         amNONE,         1 },
  { 0x19, "rr",         amREGC,         amNONE,         1 },
  { 0x1a, "rr",         amREGD,         amNONE,         1 },
  { 0x1b, "rr",         amREGE,         amNONE,         1 },
  { 0x1c, "rr",         amREGH,         amNONE,         1 },
  { 0x1d, "rr",         amREGL,         amNONE,         1 },
  { 0x1e, "rr",         amREGINDIRECT,  amNONE,         1 },
  { 0x1f, "rr",         amREGA,         amNONE,         1 },
  { 0x20, "sla",        amREGB,         amNONE,         1 },
  { 0x21, "sla",        amREGC,         amNONE,         1 },
  { 0x22, "sla",        amREGD,         amNONE,         1 },
  { 0x23, "sla",        amREGE,         amNONE,         1 },
  { 0x24, "sla",        amREGH,         amNONE,         1 },
  { 0x25, "sla",        amREGL,         amNONE,         1 },
  { 0x26, "sla",        amREGINDIRECT,  amNONE,         1 },
  { 0x27, "sla",        amREGA,         amNONE,         1 },
  { 0x28, "sra",        amREGB,         amNONE,         1 },
  { 0x29, "sra",        amREGC,         amNONE,         1 },
  { 0x2a, "sra",        amREGD,         amNONE,         1 },
  { 0x2b, "sra",        amREGE,         amNONE,         1 },
  { 0x2c, "sra",        amREGH,         amNONE,         1 },
  { 0x2d, "sra",        amREGL,         amNONE,         1 },
  { 0x2e, "sra",        amREGINDIRECT,  amNONE,         1 },
  { 0x2f, "sra",        amREGA,         amNONE,         1 },
  { 0x30, "sll",        amREGB,         amNONE,         1 },
  { 0x31, "sll",        amREGC,         amNONE,         1 },
  { 0x32, "sll",        amREGD,         amNONE,         1 },
  { 0x33, "sll",        amREGE,         amNONE,         1 },
  { 0x34, "sll",        amREGH,         amNONE,         1 },
  { 0x35, "sll",        amREGL,         amNONE,         1 },
  { 0x36, "sll",        amREGINDIRECT,  amNONE,         1 },
  { 0x37, "sll",        amREGA,         amNONE,         1 },
  { 0x38, "srl",        amREGB,         amNONE,         1 },
  { 0x39, "srl",        amREGC,         amNONE,         1 },
  { 0x3a, "srl",        amREGD,         amNONE,         1 },
  { 0x3b, "srl",        amREGE,         amNONE,         1 },
  { 0x3c, "srl",        amREGH,         amNONE,         1 },
  { 0x3d, "srl",        amREGL,         amNONE,         1 },
  { 0x3e, "srl",        amREGINDIRECT,  amNONE,         1 },
  { 0x3f, "srl",        amREGA,         amNONE,         1 },
  { 0x40, "bit 0,",     amREGB,         amNONE,         1 },
  { 0x41, "bit 0,",     amREGC,         amNONE,         1 },
  { 0x42, "bit 0,",     amREGD,         amNONE,         1 },
  { 0x43, "bit 0,",     amREGE,         amNONE,         1 },
  { 0x44, "bit 0,",     amREGH,         amNONE,         1 },
  { 0x45, "bit 0,",     amREGL,         amNONE,         1 },
  { 0x46, "bit 0,",     amREGINDIRECT,  amNONE,         1 },
  { 0x47, "bit 0,",     amREGA,         amNONE,         1 },
  { 0x48, "bit 1,",     amREGB,         amNONE,         1 },
  { 0x49, "bit 1,",     amREGC,         amNONE,         1 },
  { 0x4a, "bit 1,",     amREGD,         amNONE,         1 },
  { 0x4b, "bit 1,",     amREGE,         amNONE,         1 },
  { 0x4c, "bit 1,",     amREGH,         amNONE,         1 },
  { 0x4d, "bit 1,",     amREGL,         amNONE,         1 },
  { 0x4e, "bit 1,",     amREGINDIRECT,  amNONE,         1 },
  { 0x4f, "bit 1,",     amREGA,         amNONE,         1 },
  { 0x50, "bit 2,",     amREGB,         amNONE,         1 },
  { 0x51, "bit 2,",     amREGC,         amNONE,         1 },
  { 0x52, "bit 2,",     amREGD,         amNONE,         1 },
  { 0x53, "bit 2,",     amREGE,         amNONE,         1 },
  { 0x54, "bit 2,",     amREGH,         amNONE,         1 },
  { 0x55, "bit 2,",     amREGL,         amNONE,         1 },
  { 0x56, "bit 2,",     amREGINDIRECT,  amNONE,         1 },
  { 0x57, "bit 2,",     amREGA,         amNONE,         1 },
  { 0x58, "bit 3,",     amREGB,         amNONE,         1 },
  { 0x59, "bit 3,",     amREGC,         amNONE,         1 },
  { 0x5a, "bit 3,",     amREGD,         amNONE,         1 },
  { 0x5b, "bit 3,",     amREGE,         amNONE,         1 },
  { 0x5c, "bit 3,",     amREGH,         amNONE,         1 },
  { 0x5d, "bit 3,",     amREGL,         amNONE,         1 },
  { 0x5e, "bit 3,",     amREGINDIRECT,  amNONE,         1 },
  { 0x5f, "bit 3,",     amREGA,         amNONE,         1 },
  { 0x60, "bit 4,",     amREGB,         amNONE,         1 },
  { 0x61, "bit 4,",     amREGC,         amNONE,         1 },
  { 0x62, "bit 4,",     amREGD,         amNONE,         1 },
  { 0x63, "bit 4,",     amREGE,         amNONE,         1 },
  { 0x64, "bit 4,",     amREGH,         amNONE,         1 },
  { 0x65, "bit 4,",     amREGL,         amNONE,         1 },
  { 0x66, "bit 4,",     amREGINDIRECT,  amNONE,         1 },
  { 0x67, "bit 4,",     amREGA,         amNONE,         1 },
  { 0x68, "bit 5,",     amREGB,         amNONE,         1 },
  { 0x69, "bit 5,",     amREGC,         amNONE,         1 },
  { 0x6a, "bit 5,",     amREGD,         amNONE,         1 },
  { 0x6b, "bit 5,",     amREGE,         amNONE,         1 },
  { 0x6c, "bit 5,",     amREGH,         amNONE,         1 },
  { 0x6d, "bit 5,",     amREGL,         amNONE,         1 },
  { 0x6e, "bit 5,",     amREGINDIRECT,  amNONE,         1 },
  { 0x6f, "bit 5,",     amREGA,         amNONE,         1 },
  { 0x70, "bit 6,",     amREGB,         amNONE,         1 },
  { 0x71, "bit 6,",     amREGC,         amNONE,         1 },
  { 0x72, "bit 6,",     amREGD,         amNONE,         1 },
  { 0x73, "bit 6,",     amREGE,         amNONE,         1 },
  { 0x74, "bit 6,",     amREGH,         amNONE,         1 },
  { 0x75, "bit 6,",     amREGL,         amNONE,         1 },
  { 0x76, "bit 6,",     amREGINDIRECT,  amNONE,         1 },
  { 0x77, "bit 6,",     amREGA,         amNONE,         1 },
  { 0x78, "bit 7,",     amREGB,         amNONE,         1 },
  { 0x79, "bit 7,",     amREGC,         amNONE,         1 },
  { 0x7a, "bit 7,",     amREGD,         amNONE,         1 },
  { 0x7b, "bit 7,",     amREGE,         amNONE,         1 },
  { 0x7c, "bit 7,",     amREGH,         amNONE,         1 },
  { 0x7d, "bit 7,",     amREGL,         amNONE,         1 },
  { 0x7e, "bit 7,",     amREGINDIRECT,  amNONE,         1 },
  { 0x7f, "bit 7,",     amREGA,         amNONE,         1 },
  { 0x80, "res 0,",     amREGB,         amNONE,         1 },
  { 0x81, "res 0,",     amREGC,         amNONE,         1 },
  { 0x82, "res 0,",     amREGD,         amNONE,         1 },
  { 0x83, "res 0,",     amREGE,         amNONE,         1 },
  { 0x84, "res 0,",     amREGH,         amNONE,         1 },
  { 0x85, "res 0,",     amREGL,         amNONE,         1 },
  { 0x86, "res 0,",     amREGINDIRECT,  amNONE,         1 },
  { 0x87, "res 0,",     amREGA,         amNONE,         1 },
  { 0x88, "res 1,",     amREGB,         amNONE,         1 },
  { 0x89, "res 1,",     amREGC,         amNONE,         1 },
  { 0x8a, "res 1,",     amREGD,         amNONE,         1 },
  { 0x8b, "res 1,",     amREGE,         amNONE,         1 },
  { 0x8c, "res 1,",     amREGH,         amNONE,         1 },
  { 0x8d, "res 1,",     amREGL,         amNONE,         1 },
  { 0x8e, "res 1,",     amREGINDIRECT,  amNONE,         1 },
  { 0x8f, "res 1,",     amREGA,         amNONE,         1 },
  { 0x90, "res 2,",     amREGB,         amNONE,         1 },
  { 0x91, "res 2,",     amREGC,         amNONE,         1 },
  { 0x92, "res 2,",     amREGD,         amNONE,         1 },
  { 0x93, "res 2,",     amREGE,         amNONE,         1 },
  { 0x94, "res 2,",     amREGH,         amNONE,         1 },
  { 0x95, "res 2,",     amREGL,         amNONE,         1 },
  { 0x96, "res 2,",     amREGINDIRECT,  amNONE,         1 },
  { 0x97, "res 2,",     amREGA,         amNONE,         1 },
  { 0x98, "res 3,",     amREGB,         amNONE,         1 },
  { 0x99, "res 3,",     amREGC,         amNONE,         1 },
  { 0x9a, "res 3,",     amREGD,         amNONE,         1 },
  { 0x9b, "res 3,",     amREGE,         amNONE,         1 },
  { 0x9c, "res 3,",     amREGH,         amNONE,         1 },
  { 0x9d, "res 3,",     amREGL,         amNONE,         1 },
  { 0x9e, "res 3,",     amREGINDIRECT,  amNONE,         1 },
  { 0x9f, "res 3,",     amREGA,         amNONE,         1 },
  { 0xa0, "res 4,",     amREGB,         amNONE,         1 },
  { 0xa1, "res 4,",     amREGC,         amNONE,         1 },
  { 0xa2, "res 4,",     amREGD,         amNONE,         1 },
  { 0xa3, "res 4,",     amREGE,         amNONE,         1 },
  { 0xa4, "res 4,",     amREGH,         amNONE,         1 },
  { 0xa5, "res 4,",     amREGL,         amNONE,         1 },
  { 0xa6, "res 4,",     amREGINDIRECT,  amNONE,         1 },
  { 0xa7, "res 4,",     amREGA,         amNONE,         1 },
  { 0xa8, "res 5,",     amREGB,         amNONE,         1 },
  { 0xa9, "res 5,",     amREGC,         amNONE,         1 },
  { 0xaa, "res 5,",     amREGD,         amNONE,         1 },
  { 0xab, "res 5,",     amREGE,         amNONE,         1 },
  { 0xac, "res 5,",     amREGH,         amNONE,         1 },
  { 0xad, "res 5,",     amREGL,         amNONE,         1 },
  { 0xae, "res 5,",     amREGINDIRECT,  amNONE,         1 },
  { 0xaf, "res 5,",     amREGA,         amNONE,         1 },
  { 0xb0, "res 6,",     amREGB,         amNONE,         1 },
  { 0xb1, "res 6,",     amREGC,         amNONE,         1 },
  { 0xb2, "res 6,",     amREGD,         amNONE,         1 },
  { 0xb3, "res 6,",     amREGE,         amNONE,         1 },
  { 0xb4, "res 6,",     amREGH,         amNONE,         1 },
  { 0xb5, "res 6,",     amREGL,         amNONE,         1 },
  { 0xb6, "res 6,",     amREGINDIRECT,  amNONE,         1 },
  { 0xb7, "res 6,",     amREGA,         amNONE,         1 },
  { 0xb8, "res 7,",     amREGB,         amNONE,         1 },
  { 0xb9, "res 7,",     amREGC,         amNONE,         1 },
  { 0xba, "res 7,",     amREGD,         amNONE,         1 },
  { 0xbb, "res 7,",     amREGE,         amNONE,         1 },
  { 0xbc, "res 7,",     amREGH,         amNONE,         1 },
  { 0xbd, "res 7,",     amREGL,         amNONE,         1 },
  { 0xbe, "res 7,",     amREGINDIRECT,  amNONE,         1 },
  { 0xbf, "res 7,",     amREGA,         amNONE,         1 },
  { 0xc0, "set 0,",     amREGB,         amNONE,         1 },
  { 0xc1, "set 0,",     amREGC,         amNONE,         1 },
  { 0xc2, "set 0,",     amREGD,         amNONE,         1 },
  { 0xc3, "set 0,",     amREGE,         amNONE,         1 },
  { 0xc4, "set 0,",     amREGH,         amNONE,         1 },
  { 0xc5, "set 0,",     amREGL,         amNONE,         1 },
  { 0xc6, "set 0,",     amREGINDIRECT,  amNONE,         1 },
  { 0xc7, "set 0,",     amREGA,         amNONE,         1 },
  { 0xc8, "set 1,",     amREGB,         amNONE,         1 },
  { 0xc9, "set 1,",     amREGC,         amNONE,         1 },
  { 0xca, "set 1,",     amREGD,         amNONE,         1 },
  { 0xcb, "set 1,",     amREGE,         amNONE,         1 },
  { 0xcc, "set 1,",     amREGH,         amNONE,         1 },
  { 0xcd, "set 1,",     amREGL,         amNONE,         1 },
  { 0xce, "set 1,",     amREGINDIRECT,  amNONE,         1 },
  { 0xcf, "set 1,",     amREGA,         amNONE,         1 },
  { 0xd0, "set 2,",     amREGB,         amNONE,         1 },
  { 0xd1, "set 2,",     amREGC,         amNONE,         1 },
  { 0xd2, "set 2,",     amREGD,         amNONE,         1 },
  { 0xd3, "set 2,",     amREGE,         amNONE,         1 },
  { 0xd4, "set 2,",     amREGH,         amNONE,         1 },
  { 0xd5, "set 2,",     amREGL,         amNONE,         1 },
  { 0xd6, "set 2,",     amREGINDIRECT,  amNONE,         1 },
  { 0xd7, "set 2,",     amREGA,         amNONE,         1 },
  { 0xd8, "set 3,",     amREGB,         amNONE,         1 },
  { 0xd9, "set 3,",     amREGC,         amNONE,         1 },
  { 0xda, "set 3,",     amREGD,         amNONE,         1 },
  { 0xdb, "set 3,",     amREGE,         amNONE,         1 },
  { 0xdc, "set 3,",     amREGH,         amNONE,         1 },
  { 0xdd, "set 3,",     amREGL,         amNONE,         1 },
  { 0xde, "set 3,",     amREGINDIRECT,  amNONE,         1 },
  { 0xdf, "set 3,",     amREGA,         amNONE,         1 },
  { 0xe0, "set 4,",     amREGB,         amNONE,         1 },
  { 0xe1, "set 4,",     amREGC,         amNONE,         1 },
  { 0xe2, "set 4,",     amREGD,         amNONE,         1 },
  { 0xe3, "set 4,",     amREGE,         amNONE,         1 },
  { 0xe4, "set 4,",     amREGH,         amNONE,         1 },
  { 0xe5, "set 4,",     amREGL,         amNONE,         1 },
  { 0xe6, "set 4,",     amREGINDIRECT,  amNONE,         1 },
  { 0xe7, "set 4,",     amREGA,         amNONE,         1 },
  { 0xe8, "set 5,",     amREGB,         amNONE,         1 },
  { 0xe9, "set 5,",     amREGC,         amNONE,         1 },
  { 0xea, "set 5,",     amREGD,         amNONE,         1 },
  { 0xeb, "set 5,",     amREGE,         amNONE,         1 },
  { 0xec, "set 5,",     amREGH,         amNONE,         1 },
  { 0xed, "set 5,",     amREGL,         amNONE,         1 },
  { 0xee, "set 5,",     amREGINDIRECT,  amNONE,         1 },
  { 0xef, "set 5,",     amREGA,         amNONE,         1 },
  { 0xf0, "set 6,",     amREGB,         amNONE,         1 },
  { 0xf1, "set 6,",     amREGC,         amNONE,         1 },
  { 0xf2, "set 6,",     amREGD,         amNONE,         1 },
  { 0xf3, "set 6,",     amREGE,         amNONE,         1 },
  { 0xf4, "set 6,",     amREGH,         amNONE,         1 },
  { 0xf5, "set 6,",     amREGL,         amNONE,         1 },
  { 0xf6, "set 6,",     amREGINDIRECT,  amNONE,         1 },
  { 0xf7, "set 6,",     amREGA,         amNONE,         1 },
  { 0xf8, "set 7,",     amREGB,         amNONE,         1 },
  { 0xf9, "set 7,",     amREGC,         amNONE,         1 },
  { 0xfa, "set 7,",     amREGD,         amNONE,         1 },
  { 0xfb, "set 7,",     amREGE,         amNONE,         1 },
  { 0xfc, "set 7,",     amREGH,         amNONE,         1 },
  { 0xfd, "set 7,",     amREGL,         amNONE,         1 },
  { 0xfe, "set 7,",     amREGINDIRECT,  amNONE,         1 },
  { 0xff, "set 7,",     amREGA,         amNONE,         1 },
};

#endif
